create table cars (
	id INT,
	model VARCHAR(50),
	price INT,
	availability VARCHAR(50)
);
insert into cars (id, model, price, availability) values (1, 'M3', 12, false);
insert into cars (id, model, price, availability) values (2, 'Park Avenue', 12, false);
insert into cars (id, model, price, availability) values (3, 'RAV4', 66, false);
insert into cars (id, model, price, availability) values (4, 'Corvette', 84, false);
insert into cars (id, model, price, availability) values (5, 'SLK-Class', 8, false);
insert into cars (id, model, price, availability) values (6, 'Landaulet', 63, false);
insert into cars (id, model, price, availability) values (7, 'Brat', 25, true);
insert into cars (id, model, price, availability) values (8, 'Dakota Club', 84, true);
insert into cars (id, model, price, availability) values (9, 'Savana 2500', 93, false);
insert into cars (id, model, price, availability) values (10, 'Evora', 75, false);
insert into cars (id, model, price, availability) values (11, 'F350', 24, true);
insert into cars (id, model, price, availability) values (12, 'A4', 66, true);
insert into cars (id, model, price, availability) values (13, 'Topaz', 2, false);
insert into cars (id, model, price, availability) values (14, 'XC70', 29, false);
insert into cars (id, model, price, availability) values (15, 'Santa Fe', 65, true);
insert into cars (id, model, price, availability) values (16, 'Mariner', 59, true);
insert into cars (id, model, price, availability) values (17, 'MDX', 84, true);
insert into cars (id, model, price, availability) values (18, 'R-Class', 53, true);
insert into cars (id, model, price, availability) values (19, 'Charger', 22, false);
insert into cars (id, model, price, availability) values (20, 'Legacy', 5, false);
insert into cars (id, model, price, availability) values (21, 'Canyon', 33, false);
insert into cars (id, model, price, availability) values (22, 'Neon', 81, false);
insert into cars (id, model, price, availability) values (23, 'Tacoma Xtra', 94, false);
insert into cars (id, model, price, availability) values (24, 'Sierra 3500', 9, false);
insert into cars (id, model, price, availability) values (25, 'Cooper Clubman', 56, true);
insert into cars (id, model, price, availability) values (26, 'S2000', 1, false);
insert into cars (id, model, price, availability) values (27, 'Sable', 89, false);
insert into cars (id, model, price, availability) values (28, 'Pajero', 10, false);
insert into cars (id, model, price, availability) values (29, 'LR4', 30, true);
insert into cars (id, model, price, availability) values (30, 'Chevette', 40, false);
insert into cars (id, model, price, availability) values (31, 'Grand Voyager', 49, false);
insert into cars (id, model, price, availability) values (32, 'XF', 59, false);
insert into cars (id, model, price, availability) values (33, 'Cougar', 2, false);
insert into cars (id, model, price, availability) values (34, 'xD', 11, false);
insert into cars (id, model, price, availability) values (35, 'GLK-Class', 3, false);
insert into cars (id, model, price, availability) values (36, 'A4', 98, true);
insert into cars (id, model, price, availability) values (37, 'Park Avenue', 57, false);
insert into cars (id, model, price, availability) values (38, 'RL', 59, false);
insert into cars (id, model, price, availability) values (39, 'CLK-Class', 21, false);
insert into cars (id, model, price, availability) values (40, 'Lucerne', 76, false);
insert into cars (id, model, price, availability) values (41, 'A8', 10, true);
insert into cars (id, model, price, availability) values (42, '300ZX', 48, true);
insert into cars (id, model, price, availability) values (43, 'Minx Magnificent', 22, false);
insert into cars (id, model, price, availability) values (44, 'Metro', 81, true);
insert into cars (id, model, price, availability) values (45, 'Caliber', 74, true);
insert into cars (id, model, price, availability) values (46, 'W201', 94, false);
insert into cars (id, model, price, availability) values (47, 'Yaris', 33, false);
insert into cars (id, model, price, availability) values (48, 'E-Class', 73, false);
insert into cars (id, model, price, availability) values (49, '57', 71, false);
insert into cars (id, model, price, availability) values (50, 'Santa Fe', 31, false);
insert into cars (id, model, price, availability) values (51, 'Sonata', 77, true);
insert into cars (id, model, price, availability) values (52, 'H2', 33, true);
insert into cars (id, model, price, availability) values (53, 'Econoline E150', 90, true);
insert into cars (id, model, price, availability) values (54, 'Cherokee', 30, false);
insert into cars (id, model, price, availability) values (55, 'Vandura G3500', 30, false);
insert into cars (id, model, price, availability) values (56, 'Probe', 46, false);
insert into cars (id, model, price, availability) values (57, 'S80', 89, true);
insert into cars (id, model, price, availability) values (58, 'Azera', 11, false);
insert into cars (id, model, price, availability) values (59, 'Countach', 35, false);
insert into cars (id, model, price, availability) values (60, 'D250 Club', 22, false);
insert into cars (id, model, price, availability) values (61, 'Frontier', 27, true);
insert into cars (id, model, price, availability) values (62, 'Aero 8', 88, false);
insert into cars (id, model, price, availability) values (63, 'Avalanche', 30, true);
insert into cars (id, model, price, availability) values (64, 'Freelander', 11, true);
insert into cars (id, model, price, availability) values (65, 'Clubman', 90, false);
insert into cars (id, model, price, availability) values (66, 'tC', 1, true);
insert into cars (id, model, price, availability) values (67, 'Fit', 37, true);
insert into cars (id, model, price, availability) values (68, 'Leone', 38, true);
insert into cars (id, model, price, availability) values (69, 'Mustang', 78, false);
insert into cars (id, model, price, availability) values (70, 'XLR', 83, true);
insert into cars (id, model, price, availability) values (71, 'Regal', 34, true);
insert into cars (id, model, price, availability) values (72, 'Insight', 49, false);
insert into cars (id, model, price, availability) values (73, 'Roadster', 70, false);
insert into cars (id, model, price, availability) values (74, 'LTD', 40, false);
insert into cars (id, model, price, availability) values (75, 'M6', 75, false);
insert into cars (id, model, price, availability) values (76, 'Mustang', 78, false);
insert into cars (id, model, price, availability) values (77, 'E150', 79, true);
insert into cars (id, model, price, availability) values (78, 'Quest', 41, true);
insert into cars (id, model, price, availability) values (79, '1500', 47, true);
insert into cars (id, model, price, availability) values (80, 'Savana', 37, false);
insert into cars (id, model, price, availability) values (81, 'MR2', 67, true);
insert into cars (id, model, price, availability) values (82, 'Regal', 58, true);
insert into cars (id, model, price, availability) values (83, '626', 15, true);
insert into cars (id, model, price, availability) values (84, 'Explorer', 21, true);
insert into cars (id, model, price, availability) values (85, 'Corrado', 97, true);
insert into cars (id, model, price, availability) values (86, 'Galant', 80, false);
insert into cars (id, model, price, availability) values (87, 'Esteem', 89, false);
insert into cars (id, model, price, availability) values (88, 'RX', 54, true);
insert into cars (id, model, price, availability) values (89, 'Grand Prix', 37, false);
insert into cars (id, model, price, availability) values (90, 'Malibu', 7, false);
insert into cars (id, model, price, availability) values (91, 'Somerset', 15, false);
insert into cars (id, model, price, availability) values (92, '300CE', 51, true);
insert into cars (id, model, price, availability) values (93, 'LR2', 88, true);
insert into cars (id, model, price, availability) values (94, 'Prius', 18, true);
insert into cars (id, model, price, availability) values (95, 'Freestyle', 22, true);
insert into cars (id, model, price, availability) values (96, 'Forester', 21, false);
insert into cars (id, model, price, availability) values (97, 'Grand Marquis', 93, false);
insert into cars (id, model, price, availability) values (98, '300M', 94, false);
insert into cars (id, model, price, availability) values (99, 'Grand Voyager', 33, true);
insert into cars (id, model, price, availability) values (100, 'Rogue', 64, true);
insert into cars (id, model, price, availability) values (101, 'Legacy', 89, false);
insert into cars (id, model, price, availability) values (102, 'Rendezvous', 62, false);
insert into cars (id, model, price, availability) values (103, 'Navigator L', 85, true);
insert into cars (id, model, price, availability) values (104, 'Monte Carlo', 46, false);
insert into cars (id, model, price, availability) values (105, 'Mustang', 52, false);
insert into cars (id, model, price, availability) values (106, 'W201', 9, false);
insert into cars (id, model, price, availability) values (107, 'Q7', 86, true);
insert into cars (id, model, price, availability) values (108, 'Range Rover', 54, true);
insert into cars (id, model, price, availability) values (109, 'LeBaron', 18, false);
insert into cars (id, model, price, availability) values (110, 'Venza', 96, true);
insert into cars (id, model, price, availability) values (111, 'Savana', 89, true);
insert into cars (id, model, price, availability) values (112, 'B-Series', 28, false);
insert into cars (id, model, price, availability) values (113, 'Passport', 70, false);
insert into cars (id, model, price, availability) values (114, '760', 10, true);
insert into cars (id, model, price, availability) values (115, 'LR4', 31, false);
insert into cars (id, model, price, availability) values (116, 'Riviera', 17, true);
insert into cars (id, model, price, availability) values (117, '1 Series', 53, true);
insert into cars (id, model, price, availability) values (118, 'Camaro', 5, true);
insert into cars (id, model, price, availability) values (119, 'Firefly', 8, false);
insert into cars (id, model, price, availability) values (120, 'Regal', 35, true);
insert into cars (id, model, price, availability) values (121, 'S10', 33, true);
insert into cars (id, model, price, availability) values (122, 'Astro', 95, false);
insert into cars (id, model, price, availability) values (123, 'Tahoe', 36, false);
insert into cars (id, model, price, availability) values (124, 'Alpina B7', 93, false);
insert into cars (id, model, price, availability) values (125, 'Edge', 75, false);
insert into cars (id, model, price, availability) values (126, 'ES', 71, false);
insert into cars (id, model, price, availability) values (127, 'Eldorado', 86, true);
insert into cars (id, model, price, availability) values (128, 'Excel', 75, false);
insert into cars (id, model, price, availability) values (129, 'Mountaineer', 42, true);
insert into cars (id, model, price, availability) values (130, 'Ram Van 2500', 65, true);
insert into cars (id, model, price, availability) values (131, 'Grand Prix', 25, false);
insert into cars (id, model, price, availability) values (132, 'Pacifica', 68, false);
insert into cars (id, model, price, availability) values (133, 'D150', 16, false);
insert into cars (id, model, price, availability) values (134, 'Venture', 55, true);
insert into cars (id, model, price, availability) values (135, 'Navigator', 90, false);
insert into cars (id, model, price, availability) values (136, 'Wrangler', 79, true);
insert into cars (id, model, price, availability) values (137, 'Galant', 44, false);
insert into cars (id, model, price, availability) values (138, 'B-Series Plus', 48, false);
insert into cars (id, model, price, availability) values (139, 'Frontier', 70, false);
insert into cars (id, model, price, availability) values (140, 'Mustang', 50, true);
insert into cars (id, model, price, availability) values (141, 'Justy', 88, true);
insert into cars (id, model, price, availability) values (142, 'Avalon', 83, false);
insert into cars (id, model, price, availability) values (143, 'Stratus', 10, true);
insert into cars (id, model, price, availability) values (144, 'Tiburon', 57, true);
insert into cars (id, model, price, availability) values (145, 'Passat', 72, true);
insert into cars (id, model, price, availability) values (146, 'Concorde', 49, true);
insert into cars (id, model, price, availability) values (147, 'ZX2', 84, true);
insert into cars (id, model, price, availability) values (148, 'Expedition EL', 7, true);
insert into cars (id, model, price, availability) values (149, 'SC', 76, true);
insert into cars (id, model, price, availability) values (150, 'Ghost', 57, true);
insert into cars (id, model, price, availability) values (151, 'Safari', 83, true);
insert into cars (id, model, price, availability) values (152, 'Avalon', 49, true);
insert into cars (id, model, price, availability) values (153, '626', 20, false);
insert into cars (id, model, price, availability) values (154, 'Optima', 61, true);
insert into cars (id, model, price, availability) values (155, 'Rainier', 90, true);
insert into cars (id, model, price, availability) values (156, 'Prius', 32, false);
insert into cars (id, model, price, availability) values (157, 'A4', 41, false);
insert into cars (id, model, price, availability) values (158, 'Tahoe', 59, true);
insert into cars (id, model, price, availability) values (159, 'Insight', 91, false);
insert into cars (id, model, price, availability) values (160, 'NSX', 77, true);
insert into cars (id, model, price, availability) values (161, 'Sixty Special', 43, true);
insert into cars (id, model, price, availability) values (162, 'Grand Caravan', 93, true);
insert into cars (id, model, price, availability) values (163, 'Yaris', 77, false);
insert into cars (id, model, price, availability) values (164, 'Avalanche 2500', 99, false);
insert into cars (id, model, price, availability) values (165, 'Fox', 100, false);
insert into cars (id, model, price, availability) values (166, 'F150', 18, true);
insert into cars (id, model, price, availability) values (167, 'H1', 7, true);
insert into cars (id, model, price, availability) values (168, 'Accent', 63, false);
insert into cars (id, model, price, availability) values (169, 'M-Class', 64, true);
insert into cars (id, model, price, availability) values (170, 'Fox', 63, false);
insert into cars (id, model, price, availability) values (171, 'Prizm', 96, false);
insert into cars (id, model, price, availability) values (172, '944', 82, true);
insert into cars (id, model, price, availability) values (173, 'Cube', 99, false);
insert into cars (id, model, price, availability) values (174, 'I', 14, false);
insert into cars (id, model, price, availability) values (175, 'M', 27, false);
insert into cars (id, model, price, availability) values (176, '400E', 90, false);
insert into cars (id, model, price, availability) values (177, 'Caprice Classic', 50, false);
insert into cars (id, model, price, availability) values (178, 'Alero', 15, false);
insert into cars (id, model, price, availability) values (179, 'Ranger', 42, false);
insert into cars (id, model, price, availability) values (180, 'Dakota', 30, true);
insert into cars (id, model, price, availability) values (181, 'Daytona', 83, true);
insert into cars (id, model, price, availability) values (182, 'GTI', 87, false);
insert into cars (id, model, price, availability) values (183, 'Silverado 2500', 17, false);
insert into cars (id, model, price, availability) values (184, 'Tacoma Xtra', 75, false);
insert into cars (id, model, price, availability) values (185, 'XLR', 66, false);
insert into cars (id, model, price, availability) values (186, 'Cavalier', 4, true);
insert into cars (id, model, price, availability) values (187, 'Compass', 89, true);
insert into cars (id, model, price, availability) values (188, 'Escape', 39, true);
insert into cars (id, model, price, availability) values (189, 'LeMans', 83, true);
insert into cars (id, model, price, availability) values (190, 'Lancer Evolution', 72, false);
insert into cars (id, model, price, availability) values (191, 'Durango', 80, false);
insert into cars (id, model, price, availability) values (192, 'Summit', 67, true);
insert into cars (id, model, price, availability) values (193, 'Esteem', 87, false);
insert into cars (id, model, price, availability) values (194, 'Matrix', 21, true);
insert into cars (id, model, price, availability) values (195, 'Charger', 13, false);
insert into cars (id, model, price, availability) values (196, 'Loyale', 51, false);
insert into cars (id, model, price, availability) values (197, 'GTI', 82, true);
insert into cars (id, model, price, availability) values (198, 'F350', 48, false);
insert into cars (id, model, price, availability) values (199, 'Grand Cherokee', 88, true);
insert into cars (id, model, price, availability) values (200, 'Allroad', 27, false);
insert into cars (id, model, price, availability) values (201, 'XK', 75, false);
insert into cars (id, model, price, availability) values (202, '6 Series', 42, true);
insert into cars (id, model, price, availability) values (203, 'Envoy XL', 45, true);
insert into cars (id, model, price, availability) values (204, 'Wrangler', 21, true);
insert into cars (id, model, price, availability) values (205, '911', 15, false);
insert into cars (id, model, price, availability) values (206, 'G-Class', 6, true);
insert into cars (id, model, price, availability) values (207, '4Runner', 40, true);
insert into cars (id, model, price, availability) values (208, 'G55 AMG', 6, true);
insert into cars (id, model, price, availability) values (209, 'Accord Crosstour', 89, false);
insert into cars (id, model, price, availability) values (210, 'S-Class', 50, false);
insert into cars (id, model, price, availability) values (211, 'Tahoe', 34, false);
insert into cars (id, model, price, availability) values (212, 'Metro', 30, true);
insert into cars (id, model, price, availability) values (213, '300CE', 45, true);
insert into cars (id, model, price, availability) values (214, 'Impala', 53, false);
insert into cars (id, model, price, availability) values (215, 'SRX', 67, true);
insert into cars (id, model, price, availability) values (216, 'Camry', 14, true);
insert into cars (id, model, price, availability) values (217, 'Prelude', 73, false);
insert into cars (id, model, price, availability) values (218, 'Explorer Sport Trac', 5, false);
insert into cars (id, model, price, availability) values (219, 'Silverado 1500', 28, true);
insert into cars (id, model, price, availability) values (220, 'Optima', 3, true);
insert into cars (id, model, price, availability) values (221, 'X5', 83, true);
insert into cars (id, model, price, availability) values (222, 'Touareg', 56, false);
insert into cars (id, model, price, availability) values (223, 'Cordia', 78, false);
insert into cars (id, model, price, availability) values (224, 'SL-Class', 57, true);
insert into cars (id, model, price, availability) values (225, 'Suburban', 62, true);
insert into cars (id, model, price, availability) values (226, 'Pathfinder', 8, true);
insert into cars (id, model, price, availability) values (227, 'Celica', 30, false);
insert into cars (id, model, price, availability) values (228, 'Sierra Denali', 87, false);
insert into cars (id, model, price, availability) values (229, 'Ion', 60, false);
insert into cars (id, model, price, availability) values (230, 'Grand Marquis', 36, true);
insert into cars (id, model, price, availability) values (231, 'Yukon', 22, false);
insert into cars (id, model, price, availability) values (232, 'Passat', 53, false);
insert into cars (id, model, price, availability) values (233, 'Talon', 1, true);
insert into cars (id, model, price, availability) values (234, 'Civic Si', 59, false);
insert into cars (id, model, price, availability) values (235, 'Insight', 98, false);
insert into cars (id, model, price, availability) values (236, 'Grand Am', 21, false);
insert into cars (id, model, price, availability) values (237, 'G-Class', 87, false);
insert into cars (id, model, price, availability) values (238, 'Boxster', 34, false);
insert into cars (id, model, price, availability) values (239, 'F150', 6, true);
insert into cars (id, model, price, availability) values (240, 'Lancer Evolution', 5, false);
insert into cars (id, model, price, availability) values (241, 'F350', 83, false);
insert into cars (id, model, price, availability) values (242, 'Prowler', 86, true);
insert into cars (id, model, price, availability) values (243, 'Camaro', 92, true);
insert into cars (id, model, price, availability) values (244, 'XJ Series', 14, true);
insert into cars (id, model, price, availability) values (245, 'Safari', 36, true);
insert into cars (id, model, price, availability) values (246, 'HHR', 38, false);
insert into cars (id, model, price, availability) values (247, 'Bronco', 69, true);
insert into cars (id, model, price, availability) values (248, 'CTS-V', 73, false);
insert into cars (id, model, price, availability) values (249, '911', 61, true);
insert into cars (id, model, price, availability) values (250, 'MKS', 89, true);
insert into cars (id, model, price, availability) values (251, 'LS', 26, true);
insert into cars (id, model, price, availability) values (252, 'Tahoe', 6, false);
insert into cars (id, model, price, availability) values (253, 'SVX', 58, false);
insert into cars (id, model, price, availability) values (254, 'Jimmy', 70, true);
insert into cars (id, model, price, availability) values (255, 'Vibe', 53, true);
insert into cars (id, model, price, availability) values (256, 'LR2', 14, true);
insert into cars (id, model, price, availability) values (257, 'GLC', 65, false);
insert into cars (id, model, price, availability) values (258, 'Interceptor', 62, false);
insert into cars (id, model, price, availability) values (259, 'Grand Prix', 97, false);
insert into cars (id, model, price, availability) values (260, '900', 8, false);
insert into cars (id, model, price, availability) values (261, 'Ram Van 2500', 39, true);
insert into cars (id, model, price, availability) values (262, 'riolet', 77, true);
insert into cars (id, model, price, availability) values (263, 'Century', 32, false);
insert into cars (id, model, price, availability) values (264, 'T100', 38, false);
insert into cars (id, model, price, availability) values (265, 'SLK-Class', 66, false);
insert into cars (id, model, price, availability) values (266, 'Sierra 2500', 87, true);
insert into cars (id, model, price, availability) values (267, 'CR-V', 10, false);
insert into cars (id, model, price, availability) values (268, 'Escalade EXT', 43, true);
insert into cars (id, model, price, availability) values (269, 'RX-8', 22, false);
insert into cars (id, model, price, availability) values (270, '545', 56, false);
insert into cars (id, model, price, availability) values (271, 'Grand Caravan', 10, true);
insert into cars (id, model, price, availability) values (272, 'Ranger', 56, false);
insert into cars (id, model, price, availability) values (273, 'Civic', 83, true);
insert into cars (id, model, price, availability) values (274, 'MKX', 89, false);
insert into cars (id, model, price, availability) values (275, 'Eldorado', 2, false);
insert into cars (id, model, price, availability) values (276, 'C-Class', 83, false);
insert into cars (id, model, price, availability) values (277, 'Element', 15, true);
insert into cars (id, model, price, availability) values (278, 'Discovery', 31, false);
insert into cars (id, model, price, availability) values (279, 'TL', 20, false);
insert into cars (id, model, price, availability) values (280, 'Oasis', 93, true);
insert into cars (id, model, price, availability) values (281, 'R32', 6, true);
insert into cars (id, model, price, availability) values (282, 'T100', 38, true);
insert into cars (id, model, price, availability) values (283, 'Lancer Evolution', 7, true);
insert into cars (id, model, price, availability) values (284, 'G3', 94, false);
insert into cars (id, model, price, availability) values (285, 'Sienna', 35, false);
insert into cars (id, model, price, availability) values (286, 'Suburban 1500', 92, true);
insert into cars (id, model, price, availability) values (287, 'Electra', 31, false);
insert into cars (id, model, price, availability) values (288, 'Fusion', 37, false);
insert into cars (id, model, price, availability) values (289, 'Tacoma', 20, true);
insert into cars (id, model, price, availability) values (290, 'GTO', 84, true);
insert into cars (id, model, price, availability) values (291, 'Dakota', 4, true);
insert into cars (id, model, price, availability) values (292, 'S-Series', 74, true);
insert into cars (id, model, price, availability) values (293, 'Magnum', 39, true);
insert into cars (id, model, price, availability) values (294, 'Lancer Evolution', 27, false);
insert into cars (id, model, price, availability) values (295, 'Miata MX-5', 37, true);
insert into cars (id, model, price, availability) values (296, 'Ram 2500', 46, false);
insert into cars (id, model, price, availability) values (297, 'Type 2', 46, true);
insert into cars (id, model, price, availability) values (298, '928', 73, true);
insert into cars (id, model, price, availability) values (299, 'SL-Class', 33, true);
insert into cars (id, model, price, availability) values (300, 'Safari', 6, true);
insert into cars (id, model, price, availability) values (301, 'Grand Voyager', 31, false);
insert into cars (id, model, price, availability) values (302, 'CR-X', 30, true);
insert into cars (id, model, price, availability) values (303, 'Grand Prix', 14, true);
insert into cars (id, model, price, availability) values (304, 'Yukon XL 1500', 53, true);
insert into cars (id, model, price, availability) values (305, 'Fox', 61, false);
insert into cars (id, model, price, availability) values (306, 'Prowler', 31, true);
insert into cars (id, model, price, availability) values (307, 'Legacy', 4, false);
insert into cars (id, model, price, availability) values (308, 'XLR', 22, true);
insert into cars (id, model, price, availability) values (309, 'IS F', 62, false);
insert into cars (id, model, price, availability) values (310, 'Concorde', 99, true);
insert into cars (id, model, price, availability) values (311, 'Montero', 10, false);
insert into cars (id, model, price, availability) values (312, 'Neon', 35, true);
insert into cars (id, model, price, availability) values (313, 'Lancer', 41, true);
insert into cars (id, model, price, availability) values (314, 'Eclipse', 71, false);
insert into cars (id, model, price, availability) values (315, 'Rogue', 87, false);
insert into cars (id, model, price, availability) values (316, 'Tacoma Xtra', 55, true);
insert into cars (id, model, price, availability) values (317, 'V70', 8, false);
insert into cars (id, model, price, availability) values (318, 'Prius', 81, false);
insert into cars (id, model, price, availability) values (319, 'Prelude', 17, false);
insert into cars (id, model, price, availability) values (320, 'Bonneville', 86, true);
insert into cars (id, model, price, availability) values (321, 'S60', 67, true);
insert into cars (id, model, price, availability) values (322, 'M', 6, false);
insert into cars (id, model, price, availability) values (323, 'Firefly', 45, false);
insert into cars (id, model, price, availability) values (324, 'Ram 2500', 14, true);
insert into cars (id, model, price, availability) values (325, 'Journey', 93, false);
insert into cars (id, model, price, availability) values (326, 'Escape', 50, true);
insert into cars (id, model, price, availability) values (327, 'Riviera', 72, true);
insert into cars (id, model, price, availability) values (328, 'CTS', 61, false);
insert into cars (id, model, price, availability) values (329, 'Maxima', 30, true);
insert into cars (id, model, price, availability) values (330, 'S40', 1, true);
insert into cars (id, model, price, availability) values (331, 'W126', 29, false);
insert into cars (id, model, price, availability) values (332, 'rio', 6, true);
insert into cars (id, model, price, availability) values (333, 'Samurai', 46, false);
insert into cars (id, model, price, availability) values (334, 'Sable', 42, false);
insert into cars (id, model, price, availability) values (335, '968', 19, false);
insert into cars (id, model, price, availability) values (336, 'Scoupe', 89, true);
insert into cars (id, model, price, availability) values (337, 'Sidekick', 54, true);
insert into cars (id, model, price, availability) values (338, 'Milan', 51, true);
insert into cars (id, model, price, availability) values (339, 'Prelude', 61, false);
insert into cars (id, model, price, availability) values (340, 'Camry', 46, false);
insert into cars (id, model, price, availability) values (341, 'Starion', 63, false);
insert into cars (id, model, price, availability) values (342, 'Range Rover Classic', 58, false);
insert into cars (id, model, price, availability) values (343, 'Golf', 22, true);
insert into cars (id, model, price, availability) values (344, 'Cobalt', 68, true);
insert into cars (id, model, price, availability) values (345, 'Eclipse', 20, false);
insert into cars (id, model, price, availability) values (346, 'CX-7', 90, true);
insert into cars (id, model, price, availability) values (347, 'Camaro', 64, false);
insert into cars (id, model, price, availability) values (348, 'Discovery', 37, false);
insert into cars (id, model, price, availability) values (349, 'Tiburon', 49, true);
insert into cars (id, model, price, availability) values (350, 'Range Rover', 64, true);
insert into cars (id, model, price, availability) values (351, '200SX', 5, true);
insert into cars (id, model, price, availability) values (352, 'SL-Class', 66, true);
insert into cars (id, model, price, availability) values (353, 'G35', 56, true);
insert into cars (id, model, price, availability) values (354, 'Dakota Club', 51, true);
insert into cars (id, model, price, availability) values (355, 'Corvette', 77, true);
insert into cars (id, model, price, availability) values (356, '6 Series', 69, false);
insert into cars (id, model, price, availability) values (357, 'Corolla', 35, false);
insert into cars (id, model, price, availability) values (358, '914', 82, true);
insert into cars (id, model, price, availability) values (359, 'Regal', 26, false);
insert into cars (id, model, price, availability) values (360, 'Corvette', 20, true);
insert into cars (id, model, price, availability) values (361, 'Grand Marquis', 29, true);
insert into cars (id, model, price, availability) values (362, 'Santa Fe', 100, false);
insert into cars (id, model, price, availability) values (363, 'Titan', 60, true);
insert into cars (id, model, price, availability) values (364, 'Aurora', 72, true);
insert into cars (id, model, price, availability) values (365, 'Grand Caravan', 34, true);
insert into cars (id, model, price, availability) values (366, 'Ram 50', 45, false);
insert into cars (id, model, price, availability) values (367, 'Thunderbird', 61, true);
insert into cars (id, model, price, availability) values (368, 'Equinox', 96, false);
insert into cars (id, model, price, availability) values (369, 'Suburban 2500', 94, false);
insert into cars (id, model, price, availability) values (370, 'FX', 88, true);
insert into cars (id, model, price, availability) values (371, 'Grand Voyager', 50, true);
insert into cars (id, model, price, availability) values (372, 'Legacy', 72, true);
insert into cars (id, model, price, availability) values (373, 'Blackwood', 94, false);
insert into cars (id, model, price, availability) values (374, '300TE', 8, true);
insert into cars (id, model, price, availability) values (375, '500E', 34, true);
insert into cars (id, model, price, availability) values (376, 'Yukon XL 2500', 16, false);
insert into cars (id, model, price, availability) values (377, 'Vanagon', 68, false);
insert into cars (id, model, price, availability) values (378, '500', 86, false);
insert into cars (id, model, price, availability) values (379, 'Tahoe', 15, false);
insert into cars (id, model, price, availability) values (380, 'Trans Sport', 39, true);
insert into cars (id, model, price, availability) values (381, 'Suburban 2500', 13, true);
insert into cars (id, model, price, availability) values (382, 'Oasis', 30, true);
insert into cars (id, model, price, availability) values (383, 'Matrix', 52, true);
insert into cars (id, model, price, availability) values (384, 'SL-Class', 82, true);
insert into cars (id, model, price, availability) values (385, '3500', 84, false);
insert into cars (id, model, price, availability) values (386, 'Jimmy', 30, false);
insert into cars (id, model, price, availability) values (387, 'QX', 64, true);
insert into cars (id, model, price, availability) values (388, 'Charger', 41, true);
insert into cars (id, model, price, availability) values (389, 'Ipsum', 19, false);
insert into cars (id, model, price, availability) values (390, 'XLR-V', 63, false);
insert into cars (id, model, price, availability) values (391, 'Grand Cherokee', 34, false);
insert into cars (id, model, price, availability) values (392, 'Sunfire', 49, false);
insert into cars (id, model, price, availability) values (393, 'Suburban 2500', 25, false);
insert into cars (id, model, price, availability) values (394, 'Avanti', 54, true);
insert into cars (id, model, price, availability) values (395, '300SE', 23, true);
insert into cars (id, model, price, availability) values (396, 'Golf', 1, false);
insert into cars (id, model, price, availability) values (397, 'Esteem', 50, false);
insert into cars (id, model, price, availability) values (398, 'Escort', 97, false);
insert into cars (id, model, price, availability) values (399, 'Escort', 60, true);
insert into cars (id, model, price, availability) values (400, 'XLR', 90, false);
insert into cars (id, model, price, availability) values (401, '2500', 88, false);
insert into cars (id, model, price, availability) values (402, 'F-Series', 95, false);
insert into cars (id, model, price, availability) values (403, 'Camry', 18, true);
insert into cars (id, model, price, availability) values (404, 'Q', 8, false);
insert into cars (id, model, price, availability) values (405, '1500', 20, false);
insert into cars (id, model, price, availability) values (406, 'Regal', 30, false);
insert into cars (id, model, price, availability) values (407, 'Riviera', 94, false);
insert into cars (id, model, price, availability) values (408, 'Express 3500', 24, true);
insert into cars (id, model, price, availability) values (409, 'Sportage', 77, false);
insert into cars (id, model, price, availability) values (410, 'Capri', 38, true);
insert into cars (id, model, price, availability) values (411, 'Impala', 25, false);
insert into cars (id, model, price, availability) values (412, 'Tundra', 89, false);
insert into cars (id, model, price, availability) values (413, 'Tundra', 83, false);
insert into cars (id, model, price, availability) values (414, 'SJ', 32, true);
insert into cars (id, model, price, availability) values (415, 'xB', 51, false);
insert into cars (id, model, price, availability) values (416, 'Brat', 20, false);
insert into cars (id, model, price, availability) values (417, 'Forester', 75, true);
insert into cars (id, model, price, availability) values (418, 'Tribute', 67, true);
insert into cars (id, model, price, availability) values (419, 'Achieva', 99, false);
insert into cars (id, model, price, availability) values (420, 'Electra', 13, false);
insert into cars (id, model, price, availability) values (421, 'A8', 11, false);
insert into cars (id, model, price, availability) values (422, 'Montego', 36, false);
insert into cars (id, model, price, availability) values (423, '2500', 7, false);
insert into cars (id, model, price, availability) values (424, 'Cherokee', 42, false);
insert into cars (id, model, price, availability) values (425, 'Spectra', 20, true);
insert into cars (id, model, price, availability) values (426, 'GTO', 90, true);
insert into cars (id, model, price, availability) values (427, 'Acadia', 26, false);
insert into cars (id, model, price, availability) values (428, 'Acclaim', 15, true);
insert into cars (id, model, price, availability) values (429, 'Ram', 68, true);
insert into cars (id, model, price, availability) values (430, 'MPV', 84, false);
insert into cars (id, model, price, availability) values (431, '280ZX', 59, true);
insert into cars (id, model, price, availability) values (432, 'Rainier', 69, true);
insert into cars (id, model, price, availability) values (433, 'DB9', 37, true);
insert into cars (id, model, price, availability) values (434, 'Villager', 66, false);
insert into cars (id, model, price, availability) values (435, 'Sky', 23, false);
insert into cars (id, model, price, availability) values (436, 'Mighty Max Macro', 59, true);
insert into cars (id, model, price, availability) values (437, 'S2000', 18, true);
insert into cars (id, model, price, availability) values (438, 'S80', 57, true);
insert into cars (id, model, price, availability) values (439, 'Alero', 82, false);
insert into cars (id, model, price, availability) values (440, 'E-Series', 12, true);
insert into cars (id, model, price, availability) values (441, 'MPV', 46, true);
insert into cars (id, model, price, availability) values (442, 'Caprice Classic', 67, true);
insert into cars (id, model, price, availability) values (443, 'Avalon', 99, true);
insert into cars (id, model, price, availability) values (444, 'Swift', 4, false);
insert into cars (id, model, price, availability) values (445, 'H1', 15, false);
insert into cars (id, model, price, availability) values (446, 'CR-V', 31, false);
insert into cars (id, model, price, availability) values (447, 'SL-Class', 29, true);
insert into cars (id, model, price, availability) values (448, 'Patriot', 17, false);
insert into cars (id, model, price, availability) values (449, 'Silverado 3500', 65, false);
insert into cars (id, model, price, availability) values (450, 'Discovery', 42, true);
insert into cars (id, model, price, availability) values (451, 'Dakota Club', 50, false);
insert into cars (id, model, price, availability) values (452, 'Hombre Space', 26, false);
insert into cars (id, model, price, availability) values (453, 'Aviator', 78, true);
insert into cars (id, model, price, availability) values (454, 'Viper', 8, false);
insert into cars (id, model, price, availability) values (455, 'Civic GX', 6, true);
insert into cars (id, model, price, availability) values (456, 'SL65 AMG', 2, true);
insert into cars (id, model, price, availability) values (457, 'Seville', 13, false);
insert into cars (id, model, price, availability) values (458, '200SX', 82, false);
insert into cars (id, model, price, availability) values (459, 'Dakota Club', 88, false);
insert into cars (id, model, price, availability) values (460, 'Escape', 70, false);
insert into cars (id, model, price, availability) values (461, 'Sorento', 46, false);
insert into cars (id, model, price, availability) values (462, 'Tacoma', 47, true);
insert into cars (id, model, price, availability) values (463, 'Skyhawk', 14, false);
insert into cars (id, model, price, availability) values (464, 'Grand Cherokee', 73, true);
insert into cars (id, model, price, availability) values (465, 'Town & Country', 2, false);
insert into cars (id, model, price, availability) values (466, 'Safari', 13, true);
insert into cars (id, model, price, availability) values (467, 'Thunderbird', 35, false);
insert into cars (id, model, price, availability) values (468, 'S5', 82, true);
insert into cars (id, model, price, availability) values (469, 'Lumina', 8, true);
insert into cars (id, model, price, availability) values (470, 'Neon', 4, true);
insert into cars (id, model, price, availability) values (471, 'Traverse', 38, false);
insert into cars (id, model, price, availability) values (472, 'A3', 37, true);
insert into cars (id, model, price, availability) values (473, 'LaCrosse', 84, true);
insert into cars (id, model, price, availability) values (474, 'Villager', 53, true);
insert into cars (id, model, price, availability) values (475, 'Lucerne', 56, true);
insert into cars (id, model, price, availability) values (476, 'SC', 38, false);
insert into cars (id, model, price, availability) values (477, 'Sunbird', 39, true);
insert into cars (id, model, price, availability) values (478, 'A8', 68, true);
insert into cars (id, model, price, availability) values (479, 'Concorde', 26, false);
insert into cars (id, model, price, availability) values (480, 'Savana Cargo Van', 57, true);
insert into cars (id, model, price, availability) values (481, '3500', 68, false);
insert into cars (id, model, price, availability) values (482, 'Neon', 75, false);
insert into cars (id, model, price, availability) values (483, 'Magnum', 73, false);
insert into cars (id, model, price, availability) values (484, 'ES', 27, false);
insert into cars (id, model, price, availability) values (485, 'Tundra', 37, false);
insert into cars (id, model, price, availability) values (486, 'XC70', 36, false);
insert into cars (id, model, price, availability) values (487, 'Q7', 33, false);
insert into cars (id, model, price, availability) values (488, '530', 43, false);
insert into cars (id, model, price, availability) values (489, 'Monte Carlo', 94, false);
insert into cars (id, model, price, availability) values (490, 'Loyale', 25, false);
insert into cars (id, model, price, availability) values (491, 'Yukon Denali', 85, false);
insert into cars (id, model, price, availability) values (492, 'Rodeo', 77, true);
insert into cars (id, model, price, availability) values (493, 'Starion', 31, false);
insert into cars (id, model, price, availability) values (494, 'Maxima', 24, false);
insert into cars (id, model, price, availability) values (495, 'Town Car', 96, true);
insert into cars (id, model, price, availability) values (496, 'RX-7', 29, false);
insert into cars (id, model, price, availability) values (497, 'SC', 70, false);
insert into cars (id, model, price, availability) values (498, 'E250', 12, true);
insert into cars (id, model, price, availability) values (499, 'XLR-V', 74, false);
insert into cars (id, model, price, availability) values (500, 'Savana 3500', 93, false);
insert into cars (id, model, price, availability) values (501, 'Suburban 2500', 41, false);
insert into cars (id, model, price, availability) values (502, 'RX', 16, false);
insert into cars (id, model, price, availability) values (503, 'Brat', 49, false);
insert into cars (id, model, price, availability) values (504, 'Aspen', 4, false);
insert into cars (id, model, price, availability) values (505, 'SLK-Class', 30, false);
insert into cars (id, model, price, availability) values (506, 'V8 Vantage', 30, false);
insert into cars (id, model, price, availability) values (507, 'Taurus', 7, false);
insert into cars (id, model, price, availability) values (508, 'Grand Cherokee', 6, true);
insert into cars (id, model, price, availability) values (509, 'Protege', 34, false);
insert into cars (id, model, price, availability) values (510, 'Optima', 73, true);
insert into cars (id, model, price, availability) values (511, 'Ram 3500', 94, false);
insert into cars (id, model, price, availability) values (512, 'Grand Prix', 92, false);
insert into cars (id, model, price, availability) values (513, 'Daewoo Lacetti', 68, true);
insert into cars (id, model, price, availability) values (514, 'Optima', 46, false);
insert into cars (id, model, price, availability) values (515, 'Tundra', 37, false);
insert into cars (id, model, price, availability) values (516, 'Azera', 58, true);
insert into cars (id, model, price, availability) values (517, 'Grand Vitara', 44, false);
insert into cars (id, model, price, availability) values (518, 'Equus', 32, false);
insert into cars (id, model, price, availability) values (519, 'ZX2', 30, false);
insert into cars (id, model, price, availability) values (520, 'Allroad', 54, false);
insert into cars (id, model, price, availability) values (521, 'Tiburon', 24, false);
insert into cars (id, model, price, availability) values (522, 'Corvair', 47, false);
insert into cars (id, model, price, availability) values (523, 'Fleetwood', 20, true);
insert into cars (id, model, price, availability) values (524, 'ES', 59, true);
insert into cars (id, model, price, availability) values (525, 'S10', 11, false);
insert into cars (id, model, price, availability) values (526, 'E250', 55, true);
insert into cars (id, model, price, availability) values (527, 'M5', 80, false);
insert into cars (id, model, price, availability) values (528, 'Thunderbird', 63, false);
insert into cars (id, model, price, availability) values (529, 'Navigator', 32, false);
insert into cars (id, model, price, availability) values (530, '911', 10, false);
insert into cars (id, model, price, availability) values (531, '1500 Club Coupe', 57, false);
insert into cars (id, model, price, availability) values (532, 'Boxster', 82, true);
insert into cars (id, model, price, availability) values (533, 'Biturbo', 24, false);
insert into cars (id, model, price, availability) values (534, 'G-Series G10', 14, true);
insert into cars (id, model, price, availability) values (535, 'Corvette', 1, false);
insert into cars (id, model, price, availability) values (536, 'Thunderbird', 11, false);
insert into cars (id, model, price, availability) values (537, 'LR2', 89, false);
insert into cars (id, model, price, availability) values (538, 'Dakota Club', 80, true);
insert into cars (id, model, price, availability) values (539, 'Accord', 97, false);
insert into cars (id, model, price, availability) values (540, 'Civic', 93, false);
insert into cars (id, model, price, availability) values (541, 'F450', 98, false);
insert into cars (id, model, price, availability) values (542, '88', 39, false);
insert into cars (id, model, price, availability) values (543, 'Caprice Classic', 98, true);
insert into cars (id, model, price, availability) values (544, 'Phantom', 97, false);
insert into cars (id, model, price, availability) values (545, 'Viper', 49, true);
insert into cars (id, model, price, availability) values (546, 'New Beetle', 79, true);
insert into cars (id, model, price, availability) values (547, 'Explorer Sport Trac', 35, false);
insert into cars (id, model, price, availability) values (548, 'Liberty', 44, false);
insert into cars (id, model, price, availability) values (549, 'TT', 84, true);
insert into cars (id, model, price, availability) values (550, 'Taurus', 53, true);
insert into cars (id, model, price, availability) values (551, 'Panamera', 17, true);
insert into cars (id, model, price, availability) values (552, 'Taurus', 16, true);
insert into cars (id, model, price, availability) values (553, 'Miata MX-5', 56, true);
insert into cars (id, model, price, availability) values (554, 'PT Cruiser', 43, false);
insert into cars (id, model, price, availability) values (555, 'Seville', 21, false);
insert into cars (id, model, price, availability) values (556, 'Bravada', 29, false);
insert into cars (id, model, price, availability) values (557, 'Tracer', 81, true);
insert into cars (id, model, price, availability) values (558, 'Silhouette', 51, false);
insert into cars (id, model, price, availability) values (559, 'S60', 66, false);
insert into cars (id, model, price, availability) values (560, 'RX-7', 93, true);
insert into cars (id, model, price, availability) values (561, 'XC90', 44, true);
insert into cars (id, model, price, availability) values (562, 'E-350 Super Duty Van', 32, false);
insert into cars (id, model, price, availability) values (563, '2500', 41, false);
insert into cars (id, model, price, availability) values (564, '350Z', 87, true);
insert into cars (id, model, price, availability) values (565, 'A4', 68, false);
insert into cars (id, model, price, availability) values (566, 'Sonoma', 79, false);
insert into cars (id, model, price, availability) values (567, 'X5', 26, true);
insert into cars (id, model, price, availability) values (568, 'Mighty Max Macro', 81, true);
insert into cars (id, model, price, availability) values (569, 'Odyssey', 79, false);
insert into cars (id, model, price, availability) values (570, 'GS', 20, true);
insert into cars (id, model, price, availability) values (571, 'CL-Class', 61, true);
insert into cars (id, model, price, availability) values (572, 'Corvette', 55, false);
insert into cars (id, model, price, availability) values (573, 'CTS', 54, false);
insert into cars (id, model, price, availability) values (574, 'MX-5', 8, false);
insert into cars (id, model, price, availability) values (575, 'Q', 55, true);
insert into cars (id, model, price, availability) values (576, 'Silverado 2500', 48, true);
insert into cars (id, model, price, availability) values (577, 'Model T', 33, true);
insert into cars (id, model, price, availability) values (578, 'Z3', 18, false);
insert into cars (id, model, price, availability) values (579, 'i-290', 37, true);
insert into cars (id, model, price, availability) values (580, 'Solstice', 73, true);
insert into cars (id, model, price, availability) values (581, 'Firebird', 8, true);
insert into cars (id, model, price, availability) values (582, 'E-Series', 38, false);
insert into cars (id, model, price, availability) values (583, 'L300', 58, false);
insert into cars (id, model, price, availability) values (584, 'SL-Class', 85, true);
insert into cars (id, model, price, availability) values (585, 'Tribeca', 80, false);
insert into cars (id, model, price, availability) values (586, 'Galant', 67, false);
insert into cars (id, model, price, availability) values (587, 'Liberty', 80, true);
insert into cars (id, model, price, availability) values (588, '929', 44, true);
insert into cars (id, model, price, availability) values (589, 'F350', 31, false);
insert into cars (id, model, price, availability) values (590, 'Explorer', 3, true);
insert into cars (id, model, price, availability) values (591, 'Volare', 58, false);
insert into cars (id, model, price, availability) values (592, 'ZDX', 30, true);
insert into cars (id, model, price, availability) values (593, 'Tempo', 46, false);
insert into cars (id, model, price, availability) values (594, 'Mentor', 50, false);
insert into cars (id, model, price, availability) values (595, 'RDX', 45, false);
insert into cars (id, model, price, availability) values (596, 'Envoy', 57, false);
insert into cars (id, model, price, availability) values (597, 'Discovery', 74, true);
insert into cars (id, model, price, availability) values (598, 'C70', 88, false);
insert into cars (id, model, price, availability) values (599, 'Cabriolet', 20, false);
insert into cars (id, model, price, availability) values (600, 'XC90', 59, false);
insert into cars (id, model, price, availability) values (601, 'Tracker', 84, false);
insert into cars (id, model, price, availability) values (602, 'Patriot', 74, true);
insert into cars (id, model, price, availability) values (603, 'Viper', 52, false);
insert into cars (id, model, price, availability) values (604, 'Sierra 3500', 40, false);
insert into cars (id, model, price, availability) values (605, 'Concorde', 2, false);
insert into cars (id, model, price, availability) values (606, 'Fortwo', 56, false);
insert into cars (id, model, price, availability) values (607, 'Jetta', 83, true);
insert into cars (id, model, price, availability) values (608, 'Prelude', 90, false);
insert into cars (id, model, price, availability) values (609, 'RX', 13, true);
insert into cars (id, model, price, availability) values (610, 'Grand Prix', 48, false);
insert into cars (id, model, price, availability) values (611, 'GL-Class', 95, true);
insert into cars (id, model, price, availability) values (612, 'Corvette', 46, true);
insert into cars (id, model, price, availability) values (613, 'Continental Mark VII', 2, false);
insert into cars (id, model, price, availability) values (614, '929', 15, false);
insert into cars (id, model, price, availability) values (615, 'Grand Prix', 56, true);
insert into cars (id, model, price, availability) values (616, 'Ranger', 89, true);
insert into cars (id, model, price, availability) values (617, '9-7X', 89, true);
insert into cars (id, model, price, availability) values (618, 'Spectra', 54, false);
insert into cars (id, model, price, availability) values (619, 'Vantage', 8, true);
insert into cars (id, model, price, availability) values (620, 'A4', 62, true);
insert into cars (id, model, price, availability) values (621, 'Ram 3500', 15, true);
insert into cars (id, model, price, availability) values (622, 'Ascender', 29, true);
insert into cars (id, model, price, availability) values (623, 'R32', 61, false);
insert into cars (id, model, price, availability) values (624, '3500', 28, true);
insert into cars (id, model, price, availability) values (625, '300SL', 76, true);
insert into cars (id, model, price, availability) values (626, '350Z', 23, true);
insert into cars (id, model, price, availability) values (627, 'Jetta', 10, true);
insert into cars (id, model, price, availability) values (628, '750', 46, false);
insert into cars (id, model, price, availability) values (629, 'Intrepid', 37, true);
insert into cars (id, model, price, availability) values (630, 'Spectra', 53, false);
insert into cars (id, model, price, availability) values (631, 'Accord', 83, true);
insert into cars (id, model, price, availability) values (632, 'Roadmaster', 84, false);
insert into cars (id, model, price, availability) values (633, 'Cougar', 17, true);
insert into cars (id, model, price, availability) values (634, 'Safari', 78, false);
insert into cars (id, model, price, availability) values (635, 'Silhouette', 54, true);
insert into cars (id, model, price, availability) values (636, '100', 1, false);
insert into cars (id, model, price, availability) values (637, '2500', 63, true);
insert into cars (id, model, price, availability) values (638, 'Sportvan G20', 81, true);
insert into cars (id, model, price, availability) values (639, 'Murciélago', 83, false);
insert into cars (id, model, price, availability) values (640, '911', 46, true);
insert into cars (id, model, price, availability) values (641, 'Montana SV6', 54, true);
insert into cars (id, model, price, availability) values (642, 'Challenger', 11, false);
insert into cars (id, model, price, availability) values (643, 'Sonoma Club Coupe', 87, true);
insert into cars (id, model, price, availability) values (644, 'Reliant', 58, true);
insert into cars (id, model, price, availability) values (645, 'Town Car', 24, false);
insert into cars (id, model, price, availability) values (646, 'Suburban 1500', 70, false);
insert into cars (id, model, price, availability) values (647, 'Savana 3500', 95, true);
insert into cars (id, model, price, availability) values (648, 'A8', 23, false);
insert into cars (id, model, price, availability) values (649, 'Protege', 78, true);
insert into cars (id, model, price, availability) values (650, 'E-Class', 50, true);
insert into cars (id, model, price, availability) values (651, 'XJ Series', 16, false);
insert into cars (id, model, price, availability) values (652, 'XK', 45, true);
insert into cars (id, model, price, availability) values (653, 'rio', 1, false);
insert into cars (id, model, price, availability) values (654, 'Econoline E350', 15, false);
insert into cars (id, model, price, availability) values (655, 'Murciélago', 15, false);
insert into cars (id, model, price, availability) values (656, 'Defender Ice Edition', 25, false);
insert into cars (id, model, price, availability) values (657, 'Impala', 37, true);
insert into cars (id, model, price, availability) values (658, 'Bravada', 14, true);
insert into cars (id, model, price, availability) values (659, 'Voyager', 59, true);
insert into cars (id, model, price, availability) values (660, 'RL', 44, false);
insert into cars (id, model, price, availability) values (661, 'I', 2, true);
insert into cars (id, model, price, availability) values (662, 'Dakota', 5, true);
insert into cars (id, model, price, availability) values (663, 'Cherokee', 72, true);
insert into cars (id, model, price, availability) values (664, 'Previa', 28, true);
insert into cars (id, model, price, availability) values (665, 'XC60', 43, false);
insert into cars (id, model, price, availability) values (666, 'V40', 75, false);
insert into cars (id, model, price, availability) values (667, 'G', 16, true);
insert into cars (id, model, price, availability) values (668, 'Challenger', 22, false);
insert into cars (id, model, price, availability) values (669, 'Continental Flying Spur', 86, false);
insert into cars (id, model, price, availability) values (670, 'TL', 66, false);
insert into cars (id, model, price, availability) values (671, 'Ram', 45, true);
insert into cars (id, model, price, availability) values (672, 'Swift', 83, true);
insert into cars (id, model, price, availability) values (673, 'PT Cruiser', 16, true);
insert into cars (id, model, price, availability) values (674, '3 Series', 23, false);
insert into cars (id, model, price, availability) values (675, 'Galant', 71, true);
insert into cars (id, model, price, availability) values (676, 'Milan', 1, false);
insert into cars (id, model, price, availability) values (677, 'Bravada', 82, false);
insert into cars (id, model, price, availability) values (678, 'Silverado 3500', 72, false);
insert into cars (id, model, price, availability) values (679, 'Explorer', 25, true);
insert into cars (id, model, price, availability) values (680, 'Montero', 40, true);
insert into cars (id, model, price, availability) values (681, 'Optima', 31, false);
insert into cars (id, model, price, availability) values (682, 'XC90', 77, false);
insert into cars (id, model, price, availability) values (683, 'W126', 60, false);
insert into cars (id, model, price, availability) values (684, 'Esteem', 100, true);
insert into cars (id, model, price, availability) values (685, 'MX-6', 93, true);
insert into cars (id, model, price, availability) values (686, 'Spyder', 74, false);
insert into cars (id, model, price, availability) values (687, 'M', 100, true);
insert into cars (id, model, price, availability) values (688, 'S-Type', 95, false);
insert into cars (id, model, price, availability) values (689, 'Tracer', 23, false);
insert into cars (id, model, price, availability) values (690, 'A4', 76, false);
insert into cars (id, model, price, availability) values (691, 'RAV4', 42, true);
insert into cars (id, model, price, availability) values (692, 'VUE', 38, true);
insert into cars (id, model, price, availability) values (693, 'Ram Van 1500', 36, true);
insert into cars (id, model, price, availability) values (694, 'Diablo', 84, true);
insert into cars (id, model, price, availability) values (695, 'Esprit', 2, false);
insert into cars (id, model, price, availability) values (696, 'Silhouette', 76, true);
insert into cars (id, model, price, availability) values (697, 'Roadmaster', 29, false);
insert into cars (id, model, price, availability) values (698, 'Alero', 21, false);
insert into cars (id, model, price, availability) values (699, 'GTI', 2, true);
insert into cars (id, model, price, availability) values (700, 'RL', 52, true);
insert into cars (id, model, price, availability) values (701, 'Astro', 53, false);
insert into cars (id, model, price, availability) values (702, 'MKT', 52, true);
insert into cars (id, model, price, availability) values (703, 'Ram 3500', 24, true);
insert into cars (id, model, price, availability) values (704, 'Grand Vitara', 29, true);
insert into cars (id, model, price, availability) values (705, 'Taurus', 1, true);
insert into cars (id, model, price, availability) values (706, 'ES', 95, true);
insert into cars (id, model, price, availability) values (707, 'Mazda6', 61, true);
insert into cars (id, model, price, availability) values (708, 'Aztek', 19, true);
insert into cars (id, model, price, availability) values (709, 'E150', 30, true);
insert into cars (id, model, price, availability) values (710, 'Mulsanne', 54, true);
insert into cars (id, model, price, availability) values (711, 'Focus', 82, true);
insert into cars (id, model, price, availability) values (712, 'Biturbo', 7, false);
insert into cars (id, model, price, availability) values (713, 'Caliber', 12, true);
insert into cars (id, model, price, availability) values (714, 'Caravan', 38, true);
insert into cars (id, model, price, availability) values (715, 'TL', 89, true);
insert into cars (id, model, price, availability) values (716, '228', 11, true);
insert into cars (id, model, price, availability) values (717, 'Thunderbird', 21, true);
insert into cars (id, model, price, availability) values (718, 'Corvette', 23, false);
insert into cars (id, model, price, availability) values (719, 'Crown Victoria', 4, false);
insert into cars (id, model, price, availability) values (720, 'W126', 82, false);
insert into cars (id, model, price, availability) values (721, 'Express 2500', 10, true);
insert into cars (id, model, price, availability) values (722, 'W201', 99, false);
insert into cars (id, model, price, availability) values (723, 'Trans Sport', 86, true);
insert into cars (id, model, price, availability) values (724, 'Alpina B7', 91, false);
insert into cars (id, model, price, availability) values (725, 'Century', 29, true);
insert into cars (id, model, price, availability) values (726, 'XL-7', 11, true);
insert into cars (id, model, price, availability) values (727, 'Econoline E250', 38, true);
insert into cars (id, model, price, availability) values (728, 'A6', 61, true);
insert into cars (id, model, price, availability) values (729, 'Cordia', 85, false);
insert into cars (id, model, price, availability) values (730, 'MKT', 76, false);
insert into cars (id, model, price, availability) values (731, 'Express 2500', 22, false);
insert into cars (id, model, price, availability) values (732, '745', 7, false);
insert into cars (id, model, price, availability) values (733, 'Seville', 79, true);
insert into cars (id, model, price, availability) values (734, 'V8 Vantage S', 83, false);
insert into cars (id, model, price, availability) values (735, 'Navigator', 58, false);
insert into cars (id, model, price, availability) values (736, 'Sedona', 96, false);
insert into cars (id, model, price, availability) values (737, 'S8', 6, true);
insert into cars (id, model, price, availability) values (738, 'Esprit', 51, true);
insert into cars (id, model, price, availability) values (739, 'Legend', 71, false);
insert into cars (id, model, price, availability) values (740, 'XC70', 36, false);
insert into cars (id, model, price, availability) values (741, 'Cressida', 74, true);
insert into cars (id, model, price, availability) values (742, 'MX-5', 89, false);
insert into cars (id, model, price, availability) values (743, 'Esprit', 44, true);
insert into cars (id, model, price, availability) values (744, 'A4', 97, false);
insert into cars (id, model, price, availability) values (745, 'Xterra', 4, false);
insert into cars (id, model, price, availability) values (746, 'Eclipse', 52, true);
insert into cars (id, model, price, availability) values (747, 'Cirrus', 46, true);
insert into cars (id, model, price, availability) values (748, 'G5', 31, false);
insert into cars (id, model, price, availability) values (749, 'NSX', 16, true);
insert into cars (id, model, price, availability) values (750, 'Suburban 2500', 49, false);
insert into cars (id, model, price, availability) values (751, 'E-Class', 31, true);
insert into cars (id, model, price, availability) values (752, 'X5', 64, false);
insert into cars (id, model, price, availability) values (753, 'Ram Wagon B250', 19, true);
insert into cars (id, model, price, availability) values (754, 'F-Series', 12, false);
insert into cars (id, model, price, availability) values (755, 'LS', 22, false);
insert into cars (id, model, price, availability) values (756, 'Z3', 5, true);
insert into cars (id, model, price, availability) values (757, 'Entourage', 91, false);
insert into cars (id, model, price, availability) values (758, 'Crown Victoria', 17, true);
insert into cars (id, model, price, availability) values (759, 'Crown Victoria', 41, true);
insert into cars (id, model, price, availability) values (760, 'F-Series', 32, false);
insert into cars (id, model, price, availability) values (761, 'Concorde', 74, true);
insert into cars (id, model, price, availability) values (762, 'C8', 75, true);
insert into cars (id, model, price, availability) values (763, 'Mirage', 26, false);
insert into cars (id, model, price, availability) values (764, 'V12 Vantage', 47, true);
insert into cars (id, model, price, availability) values (765, 'Topaz', 18, false);
insert into cars (id, model, price, availability) values (766, 'IS-F', 34, true);
insert into cars (id, model, price, availability) values (767, 'Sedona', 97, true);
insert into cars (id, model, price, availability) values (768, 'C30', 32, false);
insert into cars (id, model, price, availability) values (769, 'XLR', 22, false);
insert into cars (id, model, price, availability) values (770, 'Expo', 48, false);
insert into cars (id, model, price, availability) values (771, 'Titan', 8, false);
insert into cars (id, model, price, availability) values (772, 'MDX', 38, true);
insert into cars (id, model, price, availability) values (773, 'Tacoma', 67, false);
insert into cars (id, model, price, availability) values (774, 'Quest', 38, false);
insert into cars (id, model, price, availability) values (775, 'GTO', 44, true);
insert into cars (id, model, price, availability) values (776, 'Crown Victoria', 95, false);
insert into cars (id, model, price, availability) values (777, 'RX-8', 88, true);
insert into cars (id, model, price, availability) values (778, 'Insight', 72, true);
insert into cars (id, model, price, availability) values (779, 'SLK55 AMG', 49, false);
insert into cars (id, model, price, availability) values (780, 'Laser', 30, true);
insert into cars (id, model, price, availability) values (781, 'Cobalt', 90, false);
insert into cars (id, model, price, availability) values (782, 'Seville', 97, false);
insert into cars (id, model, price, availability) values (783, 'Suburban 1500', 89, true);
insert into cars (id, model, price, availability) values (784, 'Nubira', 92, true);
insert into cars (id, model, price, availability) values (785, 'MKX', 15, true);
insert into cars (id, model, price, availability) values (786, '400SEL', 37, false);
insert into cars (id, model, price, availability) values (787, 'Mulsanne', 1, false);
insert into cars (id, model, price, availability) values (788, 'Azure T', 80, false);
insert into cars (id, model, price, availability) values (789, 'Range Rover', 61, false);
insert into cars (id, model, price, availability) values (790, 'Sprinter', 77, false);
insert into cars (id, model, price, availability) values (791, 'Gran Sport', 67, false);
insert into cars (id, model, price, availability) values (792, 'Escalade ESV', 76, true);
insert into cars (id, model, price, availability) values (793, 'Ram 2500 Club', 22, false);
insert into cars (id, model, price, availability) values (794, 'Sephia', 39, true);
insert into cars (id, model, price, availability) values (795, 'GTO', 80, false);
insert into cars (id, model, price, availability) values (796, 'GX', 56, false);
insert into cars (id, model, price, availability) values (797, 'Town Car', 2, false);
insert into cars (id, model, price, availability) values (798, 'Grand Prix', 28, true);
insert into cars (id, model, price, availability) values (799, 'Q', 77, true);
insert into cars (id, model, price, availability) values (800, 'Imperial', 50, true);
insert into cars (id, model, price, availability) values (801, 'Aveo', 29, true);
insert into cars (id, model, price, availability) values (802, 'Breeze', 5, false);
insert into cars (id, model, price, availability) values (803, 'Pilot', 23, false);
insert into cars (id, model, price, availability) values (804, 'Gallardo', 54, true);
insert into cars (id, model, price, availability) values (805, 'SL-Class', 21, true);
insert into cars (id, model, price, availability) values (806, 'Maxima', 59, false);
insert into cars (id, model, price, availability) values (807, 'Precis', 15, false);
insert into cars (id, model, price, availability) values (808, 'XK', 80, false);
insert into cars (id, model, price, availability) values (809, 'B-Series Plus', 22, false);
insert into cars (id, model, price, availability) values (810, 'Beretta', 80, false);
insert into cars (id, model, price, availability) values (811, 'RX-7', 70, false);
insert into cars (id, model, price, availability) values (812, 'Tacoma Xtra', 7, false);
insert into cars (id, model, price, availability) values (813, 'Explorer', 6, false);
insert into cars (id, model, price, availability) values (814, 'Echo', 3, false);
insert into cars (id, model, price, availability) values (815, 'H3', 99, false);
insert into cars (id, model, price, availability) values (816, '626', 55, true);
insert into cars (id, model, price, availability) values (817, 'Escalade ESV', 3, true);
insert into cars (id, model, price, availability) values (818, '760', 87, true);
insert into cars (id, model, price, availability) values (819, 'Savana 1500', 64, false);
insert into cars (id, model, price, availability) values (820, 'G-Class', 90, true);
insert into cars (id, model, price, availability) values (821, 'Galant', 92, true);
insert into cars (id, model, price, availability) values (822, 'Expo', 2, false);
insert into cars (id, model, price, availability) values (823, 'Entourage', 17, true);
insert into cars (id, model, price, availability) values (824, 'SRX', 34, true);
insert into cars (id, model, price, availability) values (825, 'Impreza', 33, false);
insert into cars (id, model, price, availability) values (826, 'Quattro', 41, false);
insert into cars (id, model, price, availability) values (827, 'Econoline E350', 3, true);
insert into cars (id, model, price, availability) values (828, 'Ion', 97, false);
insert into cars (id, model, price, availability) values (829, 'Optima', 10, false);
insert into cars (id, model, price, availability) values (830, 'Arnage', 99, false);
insert into cars (id, model, price, availability) values (831, 'RSX', 17, true);
insert into cars (id, model, price, availability) values (832, 'Silhouette', 96, false);
insert into cars (id, model, price, availability) values (833, 'CL-Class', 2, true);
insert into cars (id, model, price, availability) values (834, 'F450', 32, false);
insert into cars (id, model, price, availability) values (835, 'Dakota Club', 5, false);
insert into cars (id, model, price, availability) values (836, 'Gemini', 73, true);
insert into cars (id, model, price, availability) values (837, 'Cabriolet', 48, false);
insert into cars (id, model, price, availability) values (838, 'Mazda3', 39, true);
insert into cars (id, model, price, availability) values (839, 'Continental', 64, true);
insert into cars (id, model, price, availability) values (840, 'F150', 29, true);
insert into cars (id, model, price, availability) values (841, 'Regency', 94, true);
insert into cars (id, model, price, availability) values (842, 'Veyron', 80, true);
insert into cars (id, model, price, availability) values (843, 'Legacy', 51, true);
insert into cars (id, model, price, availability) values (844, 'SL-Class', 23, false);
insert into cars (id, model, price, availability) values (845, '911', 12, false);
insert into cars (id, model, price, availability) values (846, 'RS 4', 64, false);
insert into cars (id, model, price, availability) values (847, 'Galant', 97, true);
insert into cars (id, model, price, availability) values (848, 'Eos', 30, true);
insert into cars (id, model, price, availability) values (849, 'Sable', 55, true);
insert into cars (id, model, price, availability) values (850, 'Taurus', 25, false);
insert into cars (id, model, price, availability) values (851, 'Caprice Classic', 66, true);
insert into cars (id, model, price, availability) values (852, 'XC70', 52, true);
insert into cars (id, model, price, availability) values (853, 'Mark VIII', 54, true);
insert into cars (id, model, price, availability) values (854, 'Mazda3', 99, true);
insert into cars (id, model, price, availability) values (855, 'XLR', 44, true);
insert into cars (id, model, price, availability) values (856, 'CC', 36, false);
insert into cars (id, model, price, availability) values (857, 'RDX', 40, true);
insert into cars (id, model, price, availability) values (858, 'XJ Series', 69, true);
insert into cars (id, model, price, availability) values (859, 'MX-6', 70, true);
insert into cars (id, model, price, availability) values (860, 'Maxima', 40, true);
insert into cars (id, model, price, availability) values (861, '928', 35, false);
insert into cars (id, model, price, availability) values (862, 'Sierra 2500', 47, false);
insert into cars (id, model, price, availability) values (863, '207', 92, false);
insert into cars (id, model, price, availability) values (864, 'RX', 20, false);
insert into cars (id, model, price, availability) values (865, 'PT Cruiser', 74, true);
insert into cars (id, model, price, availability) values (866, 'Diamante', 44, true);
insert into cars (id, model, price, availability) values (867, 'S40', 66, true);
insert into cars (id, model, price, availability) values (868, 'Ranger', 35, true);
insert into cars (id, model, price, availability) values (869, 'CLS-Class', 90, false);
insert into cars (id, model, price, availability) values (870, 'A6', 66, true);
insert into cars (id, model, price, availability) values (871, 'Continental Mark VII', 33, false);
insert into cars (id, model, price, availability) values (872, 'Endeavor', 53, true);
insert into cars (id, model, price, availability) values (873, 'Montero', 49, true);
insert into cars (id, model, price, availability) values (874, 'Swift', 35, false);
insert into cars (id, model, price, availability) values (875, 'Challenger', 91, true);
insert into cars (id, model, price, availability) values (876, 'Town Car', 75, false);
insert into cars (id, model, price, availability) values (877, 'Xterra', 56, false);
insert into cars (id, model, price, availability) values (878, 'Focus', 14, false);
insert into cars (id, model, price, availability) values (879, 'RDX', 69, true);
insert into cars (id, model, price, availability) values (880, 'Prizm', 31, true);
insert into cars (id, model, price, availability) values (881, 'Cherokee', 35, false);
insert into cars (id, model, price, availability) values (882, 'xB', 11, false);
insert into cars (id, model, price, availability) values (883, 'Cavalier', 25, false);
insert into cars (id, model, price, availability) values (884, 'Exige', 1, false);
insert into cars (id, model, price, availability) values (885, 'Excursion', 92, false);
insert into cars (id, model, price, availability) values (886, 'Malibu', 90, false);
insert into cars (id, model, price, availability) values (887, '3500', 10, true);
insert into cars (id, model, price, availability) values (888, 'G37', 88, false);
insert into cars (id, model, price, availability) values (889, '9-3', 89, true);
insert into cars (id, model, price, availability) values (890, '9-3', 8, true);
insert into cars (id, model, price, availability) values (891, 'SL-Class', 1, false);
insert into cars (id, model, price, availability) values (892, 'Prizm', 60, false);
insert into cars (id, model, price, availability) values (893, 'Monterey', 54, false);
insert into cars (id, model, price, availability) values (894, 'G-Series 2500', 81, false);
insert into cars (id, model, price, availability) values (895, '944', 72, false);
insert into cars (id, model, price, availability) values (896, 'S-Type', 17, true);
insert into cars (id, model, price, availability) values (897, 'Sequoia', 18, true);
insert into cars (id, model, price, availability) values (898, 'Navajo', 67, false);
insert into cars (id, model, price, availability) values (899, 'rio', 47, true);
insert into cars (id, model, price, availability) values (900, 'Tucson', 46, false);
insert into cars (id, model, price, availability) values (901, 'Sephia', 14, true);
insert into cars (id, model, price, availability) values (902, 'Sentra', 19, false);
insert into cars (id, model, price, availability) values (903, 'S2000', 9, true);
insert into cars (id, model, price, availability) values (904, 'Ranger', 95, true);
insert into cars (id, model, price, availability) values (905, 'Fiero', 32, false);
insert into cars (id, model, price, availability) values (906, 'D150 Club', 37, true);
insert into cars (id, model, price, availability) values (907, 'TrailBlazer', 90, false);
insert into cars (id, model, price, availability) values (908, 'Aviator', 77, false);
insert into cars (id, model, price, availability) values (909, 'NV2500', 50, false);
insert into cars (id, model, price, availability) values (910, 'Esteem', 63, false);
insert into cars (id, model, price, availability) values (911, 'Journey', 56, false);
insert into cars (id, model, price, availability) values (912, 'Caravan', 78, true);
insert into cars (id, model, price, availability) values (913, 'Navigator', 48, false);
insert into cars (id, model, price, availability) values (914, 'Caprice Classic', 31, true);
insert into cars (id, model, price, availability) values (915, 'Range Rover', 73, false);
insert into cars (id, model, price, availability) values (916, 'Reventón', 49, true);
insert into cars (id, model, price, availability) values (917, 'I', 13, true);
insert into cars (id, model, price, availability) values (918, 'Century', 49, false);
insert into cars (id, model, price, availability) values (919, 'Bronco II', 66, true);
insert into cars (id, model, price, availability) values (920, 'S40', 78, true);
insert into cars (id, model, price, availability) values (921, 'LUV', 19, true);
insert into cars (id, model, price, availability) values (922, 'Venture', 59, true);
insert into cars (id, model, price, availability) values (923, 'Rio', 39, true);
insert into cars (id, model, price, availability) values (924, 'Explorer', 87, true);
insert into cars (id, model, price, availability) values (925, 'Legacy', 37, true);
insert into cars (id, model, price, availability) values (926, '6000', 32, false);
insert into cars (id, model, price, availability) values (927, 'XC70', 41, true);
insert into cars (id, model, price, availability) values (928, 'Camry Hybrid', 5, true);
insert into cars (id, model, price, availability) values (929, 'Eldorado', 94, false);
insert into cars (id, model, price, availability) values (930, 'Sentra', 65, true);
insert into cars (id, model, price, availability) values (931, 'F-Series', 76, true);
insert into cars (id, model, price, availability) values (932, 'G-Series G20', 7, true);
insert into cars (id, model, price, availability) values (933, 'MR2', 48, false);
insert into cars (id, model, price, availability) values (934, 'M', 80, true);
insert into cars (id, model, price, availability) values (935, 'Ram Van 3500', 75, false);
insert into cars (id, model, price, availability) values (936, 'F150', 71, false);
insert into cars (id, model, price, availability) values (937, 'Raider', 68, true);
insert into cars (id, model, price, availability) values (938, 'Truck', 34, false);
insert into cars (id, model, price, availability) values (939, 'Veracruz', 76, true);
insert into cars (id, model, price, availability) values (940, '960', 19, false);
insert into cars (id, model, price, availability) values (941, 'Ram Van 1500', 80, true);
insert into cars (id, model, price, availability) values (942, 'Accord', 90, false);
insert into cars (id, model, price, availability) values (943, 'RX-8', 58, false);
insert into cars (id, model, price, availability) values (944, 'F-Series', 61, true);
insert into cars (id, model, price, availability) values (945, 'Colt', 47, false);
insert into cars (id, model, price, availability) values (946, 'Camry', 80, false);
insert into cars (id, model, price, availability) values (947, 'Camry Hybrid', 84, false);
insert into cars (id, model, price, availability) values (948, 'Grand Am', 87, true);
insert into cars (id, model, price, availability) values (949, '1500 Club Coupe', 66, true);
insert into cars (id, model, price, availability) values (950, 'Ram 3500 Club', 38, false);
insert into cars (id, model, price, availability) values (951, 'Dakota Club', 26, false);
insert into cars (id, model, price, availability) values (952, 'Town Car', 25, false);
insert into cars (id, model, price, availability) values (953, 'B-Series Plus', 9, false);
insert into cars (id, model, price, availability) values (954, 'Grand Marquis', 34, true);
insert into cars (id, model, price, availability) values (955, 'RL', 86, true);
insert into cars (id, model, price, availability) values (956, 'Thunderbird', 49, false);
insert into cars (id, model, price, availability) values (957, 'del Sol', 64, true);
insert into cars (id, model, price, availability) values (958, 'V8 Vantage', 14, false);
insert into cars (id, model, price, availability) values (959, 'Sportvan G20', 95, false);
insert into cars (id, model, price, availability) values (960, 'GTO', 6, true);
insert into cars (id, model, price, availability) values (961, 'Diablo', 43, true);
insert into cars (id, model, price, availability) values (962, 'XJ', 74, false);
insert into cars (id, model, price, availability) values (963, 'Boxster', 40, false);
insert into cars (id, model, price, availability) values (964, 'Corolla', 48, false);
insert into cars (id, model, price, availability) values (965, 'Escalade EXT', 61, false);
insert into cars (id, model, price, availability) values (966, 'Previa', 5, true);
insert into cars (id, model, price, availability) values (967, 'E250', 15, true);
insert into cars (id, model, price, availability) values (968, 'TL', 22, false);
insert into cars (id, model, price, availability) values (969, 'Expo', 33, false);
insert into cars (id, model, price, availability) values (970, 'Genesis', 9, true);
insert into cars (id, model, price, availability) values (971, 'Tahoe', 23, true);
insert into cars (id, model, price, availability) values (972, 'Continental Mark VII', 84, true);
insert into cars (id, model, price, availability) values (973, '9-5', 66, true);
insert into cars (id, model, price, availability) values (974, 'DeVille', 43, false);
insert into cars (id, model, price, availability) values (975, 'Town & Country', 48, true);
insert into cars (id, model, price, availability) values (976, 'Terrain', 82, true);
insert into cars (id, model, price, availability) values (977, 'F150', 99, false);
insert into cars (id, model, price, availability) values (978, 'Countryman', 39, true);
insert into cars (id, model, price, availability) values (979, 'Xterra', 28, false);
insert into cars (id, model, price, availability) values (980, 'Miata MX-5', 16, true);
insert into cars (id, model, price, availability) values (981, 'Golf', 8, true);
insert into cars (id, model, price, availability) values (982, 'Ram 3500 Club', 86, false);
insert into cars (id, model, price, availability) values (983, 'Fiesta', 39, true);
insert into cars (id, model, price, availability) values (984, 'Silverado 3500', 24, true);
insert into cars (id, model, price, availability) values (985, 'Aviator', 87, true);
insert into cars (id, model, price, availability) values (986, 'Equus', 76, true);
insert into cars (id, model, price, availability) values (987, 'Pajero', 40, false);
insert into cars (id, model, price, availability) values (988, 'Mighty Max', 34, true);
insert into cars (id, model, price, availability) values (989, 'Acclaim', 83, false);
insert into cars (id, model, price, availability) values (990, 'QX', 22, false);
insert into cars (id, model, price, availability) values (991, 'Swift', 70, false);
insert into cars (id, model, price, availability) values (992, '645', 39, true);
insert into cars (id, model, price, availability) values (993, 'GS', 34, true);
insert into cars (id, model, price, availability) values (994, 'Sunfire', 22, false);
insert into cars (id, model, price, availability) values (995, 'Silhouette', 31, false);
insert into cars (id, model, price, availability) values (996, 'CLS-Class', 69, false);
insert into cars (id, model, price, availability) values (997, 'S10 Blazer', 42, true);
insert into cars (id, model, price, availability) values (998, 'Skylark', 93, true);
insert into cars (id, model, price, availability) values (999, 'GT500', 91, false);
insert into cars (id, model, price, availability) values (1000, 'Topaz', 84, true);
