create table mobiles (
	id INT,
	model VARCHAR(50),
	price INT,
	availability VARCHAR(50)
);
insert into mobiles (id, model, price, availability) values (1, 'Samsung E1410', 83, true);
insert into mobiles (id, model, price, availability) values (2, 'QMobile Noir Z5', 56, false);
insert into mobiles (id, model, price, availability) values (3, 'Apple iPad Wi-Fi', 28, true);
insert into mobiles (id, model, price, availability) values (4, 'Samsung B5310 CorbyPRO', 93, true);
insert into mobiles (id, model, price, availability) values (5, 'Lenovo ZUK Edge', 84, true);
insert into mobiles (id, model, price, availability) values (6, 'alcatel Pixi 3 (8) LTE', 31, true);
insert into mobiles (id, model, price, availability) values (7, 'Apple iPhone 8', 18, false);
insert into mobiles (id, model, price, availability) values (8, 'Philips W3568', 2, false);
insert into mobiles (id, model, price, availability) values (9, 'LG Watch Style', 15, true);
insert into mobiles (id, model, price, availability) values (10, 'ZTE nubia Z11 Max', 99, true);
insert into mobiles (id, model, price, availability) values (11, 'Samsung Galaxy Grand I9082', 57, true);
insert into mobiles (id, model, price, availability) values (12, 'Acer Iconia Tab A1-810', 63, true);
insert into mobiles (id, model, price, availability) values (13, 'Samsung Galaxy A72 5G', 94, false);
insert into mobiles (id, model, price, availability) values (14, 'Vodafone 835', 100, false);
insert into mobiles (id, model, price, availability) values (15, 'Maxwest MX-210TV', 100, true);
insert into mobiles (id, model, price, availability) values (16, 'VK Mobile VK1100', 70, true);
insert into mobiles (id, model, price, availability) values (17, 'verykool s732', 43, true);
insert into mobiles (id, model, price, availability) values (18, 'Motorola L6', 43, false);
insert into mobiles (id, model, price, availability) values (19, 'Nokia Mural', 85, false);
insert into mobiles (id, model, price, availability) values (20, 'Maxon MX-E10', 98, false);
insert into mobiles (id, model, price, availability) values (21, 'Spice M-5363 Boss', 89, true);
insert into mobiles (id, model, price, availability) values (22, 'T-Mobile MDA Vario IV', 32, true);
insert into mobiles (id, model, price, availability) values (23, 'i-mate Ultimate 8502', 28, true);
insert into mobiles (id, model, price, availability) values (24, 'Honor 6C Pro', 78, false);
insert into mobiles (id, model, price, availability) values (25, 'i-mobile TV 626', 95, true);
insert into mobiles (id, model, price, availability) values (26, 'Micromax Bolt Q331', 41, false);
insert into mobiles (id, model, price, availability) values (27, 'Honor 20 Pro', 72, true);
insert into mobiles (id, model, price, availability) values (28, 'Ulefone Armor X6', 70, false);
insert into mobiles (id, model, price, availability) values (29, 'Gionee Marathon M5 enjoy', 97, true);
insert into mobiles (id, model, price, availability) values (30, 'Motorola ATRIX 4G', 55, true);
insert into mobiles (id, model, price, availability) values (31, 'Nokia 7700', 78, true);
insert into mobiles (id, model, price, availability) values (32, 'Oppo A53', 39, true);
insert into mobiles (id, model, price, availability) values (33, 'Nokia Asha 230', 7, false);
insert into mobiles (id, model, price, availability) values (34, 'Acer Iconia One 7 B1-730', 34, true);
insert into mobiles (id, model, price, availability) values (35, 'Motorola Moto G Fast', 63, true);
insert into mobiles (id, model, price, availability) values (36, 'NEC e101', 4, false);
insert into mobiles (id, model, price, availability) values (37, 'Honor View 20', 36, true);
insert into mobiles (id, model, price, availability) values (38, 'Apple iPad Pro 9.7 (2016)', 19, true);
insert into mobiles (id, model, price, availability) values (39, 'Sony Ericsson W205', 49, true);
insert into mobiles (id, model, price, availability) values (40, 'ZTE Grand X Max+', 65, false);
insert into mobiles (id, model, price, availability) values (41, 'LG A258', 49, true);
insert into mobiles (id, model, price, availability) values (42, 'Lava Iris 404 Flair', 58, true);
insert into mobiles (id, model, price, availability) values (43, 'Philips Xenium F511', 66, false);
insert into mobiles (id, model, price, availability) values (44, 'ZTE Axon 20 4G', 53, false);
insert into mobiles (id, model, price, availability) values (45, 'Samsung Z330', 46, true);
insert into mobiles (id, model, price, availability) values (46, 'alcatel 3T 8', 18, true);
insert into mobiles (id, model, price, availability) values (47, 'Mitac MIO Explora K75', 43, true);
insert into mobiles (id, model, price, availability) values (48, 'Huawei Ascend P1', 44, true);
insert into mobiles (id, model, price, availability) values (49, 'Nokia C5 Endi', 69, false);
insert into mobiles (id, model, price, availability) values (50, 'Motorola Motokey Social', 83, true);
insert into mobiles (id, model, price, availability) values (51, 'BLU Studio M HD', 19, true);
insert into mobiles (id, model, price, availability) values (52, 'Micromax X560', 21, true);
insert into mobiles (id, model, price, availability) values (53, 'Celkon Campus One A354C', 53, true);
insert into mobiles (id, model, price, availability) values (54, 'Intex Aqua Power', 92, true);
insert into mobiles (id, model, price, availability) values (55, 'Sony Xperia E1', 48, true);
insert into mobiles (id, model, price, availability) values (56, 'alcatel One Touch T''Pop', 45, true);
insert into mobiles (id, model, price, availability) values (57, 'Asus Zenpad Z8s ZT582KL', 2, true);
insert into mobiles (id, model, price, availability) values (58, 'Sharp GX33', 100, false);
insert into mobiles (id, model, price, availability) values (59, 'Gionee X1', 25, true);
insert into mobiles (id, model, price, availability) values (60, 'Yezz Z50', 89, false);
insert into mobiles (id, model, price, availability) values (61, 'Nokia 500', 50, true);
insert into mobiles (id, model, price, availability) values (62, 'alcatel OT-202', 91, false);
insert into mobiles (id, model, price, availability) values (63, 'Gionee Ctrl V2', 8, true);
insert into mobiles (id, model, price, availability) values (64, 'Yezz Andy 5EI3 (2016)', 48, false);
insert into mobiles (id, model, price, availability) values (65, 'Samsung Galaxy S4 Active LTE-A', 57, false);
insert into mobiles (id, model, price, availability) values (66, 'Sagem MY C-1', 6, true);
insert into mobiles (id, model, price, availability) values (67, 'BLU Neo', 65, false);
insert into mobiles (id, model, price, availability) values (68, 'Motorola Moto G Turbo', 92, false);
insert into mobiles (id, model, price, availability) values (69, 'Karbonn Titanium S99', 31, true);
insert into mobiles (id, model, price, availability) values (70, 'QMobile Noir i12', 88, true);
insert into mobiles (id, model, price, availability) values (71, 'Archos 53 Platinum', 91, true);
insert into mobiles (id, model, price, availability) values (72, 'Micromax Canvas 5 E481', 68, false);
insert into mobiles (id, model, price, availability) values (73, 'alcatel OT-E252', 85, false);
insert into mobiles (id, model, price, availability) values (74, 'Motorola V291', 81, true);
insert into mobiles (id, model, price, availability) values (75, 'Lava A50', 82, false);
insert into mobiles (id, model, price, availability) values (76, 'Honor 10X Lite', 5, true);
insert into mobiles (id, model, price, availability) values (77, 'Siemens A65', 15, true);
insert into mobiles (id, model, price, availability) values (78, 'Asus Fonepad 7 (2014)', 26, false);
insert into mobiles (id, model, price, availability) values (79, 'Micromax X267', 76, false);
insert into mobiles (id, model, price, availability) values (80, 'Motorola W218', 55, false);
insert into mobiles (id, model, price, availability) values (81, 'Sony CMD CD5', 65, false);
insert into mobiles (id, model, price, availability) values (82, 'LG W31+', 64, true);
insert into mobiles (id, model, price, availability) values (83, 'Archos 53 Platinum', 3, true);
insert into mobiles (id, model, price, availability) values (84, 'LG KE770 Shine', 17, false);
insert into mobiles (id, model, price, availability) values (85, 'Icemobile Rock 2.4', 11, false);
insert into mobiles (id, model, price, availability) values (86, 'Apple iPad 3 Wi-Fi', 66, true);
insert into mobiles (id, model, price, availability) values (87, 'Acer Liquid Jade 2', 13, false);
insert into mobiles (id, model, price, availability) values (88, 'Philips S200', 52, true);
insert into mobiles (id, model, price, availability) values (89, 'Philips V787', 6, true);
insert into mobiles (id, model, price, availability) values (90, 'Vodafone 332', 8, true);
insert into mobiles (id, model, price, availability) values (91, 'Huawei MediaPad M6 10.8', 42, false);
insert into mobiles (id, model, price, availability) values (92, 'Allview X4 Soul Mini', 5, false);
insert into mobiles (id, model, price, availability) values (93, 'Gionee M30', 43, false);
insert into mobiles (id, model, price, availability) values (94, 'Lenovo Phab2', 82, true);
insert into mobiles (id, model, price, availability) values (95, 'Samsung M220L Galaxy Neo', 2, false);
insert into mobiles (id, model, price, availability) values (96, 'Honor 10X Lite', 37, true);
insert into mobiles (id, model, price, availability) values (97, 'Ulefone Armor X8', 66, false);
insert into mobiles (id, model, price, availability) values (98, 'NEC Terrain', 36, true);
insert into mobiles (id, model, price, availability) values (99, 'Micromax A117 Canvas Magnus', 99, false);
insert into mobiles (id, model, price, availability) values (100, 'Sony Ericsson Z710', 80, false);
insert into mobiles (id, model, price, availability) values (101, 'ZTE Tania', 38, false);
insert into mobiles (id, model, price, availability) values (102, 'Maxon MX-6899', 85, true);
insert into mobiles (id, model, price, availability) values (103, 'Allview V3 Viper', 59, false);
insert into mobiles (id, model, price, availability) values (104, 'Huawei nova 7 SE 5G Youth', 67, false);
insert into mobiles (id, model, price, availability) values (105, 'Samsung Galaxy Tab Active 2', 4, true);
insert into mobiles (id, model, price, availability) values (106, 'XCute DV2', 54, false);
insert into mobiles (id, model, price, availability) values (107, 'Toshiba TX80', 1, false);
insert into mobiles (id, model, price, availability) values (108, 'Xiaomi Redmi 9C', 49, true);
insert into mobiles (id, model, price, availability) values (109, 'alcatel OT-V270', 36, true);
insert into mobiles (id, model, price, availability) values (110, 'Micromax X291', 43, true);
insert into mobiles (id, model, price, availability) values (111, 'QMobile W1', 29, false);
insert into mobiles (id, model, price, availability) values (112, 'Motorola V290', 9, true);
insert into mobiles (id, model, price, availability) values (113, 'verykool i280', 3, true);
insert into mobiles (id, model, price, availability) values (114, 'Vodafone Tab Prime 7', 20, true);
insert into mobiles (id, model, price, availability) values (115, 'Casio G''zOne Ravine 2', 36, false);
insert into mobiles (id, model, price, availability) values (116, 'Celkon C555', 68, false);
insert into mobiles (id, model, price, availability) values (117, 'BLU Studio X', 24, true);
insert into mobiles (id, model, price, availability) values (118, 'HP iPAQ 910c', 93, true);
insert into mobiles (id, model, price, availability) values (119, 'Motorola Photon Q 4G LTE XT897', 100, false);
insert into mobiles (id, model, price, availability) values (120, 'Toshiba Excite AT200', 40, true);
insert into mobiles (id, model, price, availability) values (121, 'HTC Windows Phone 8S', 67, true);
insert into mobiles (id, model, price, availability) values (122, 'Motorola A1000', 96, false);
insert into mobiles (id, model, price, availability) values (123, 'Realme C12', 42, false);
insert into mobiles (id, model, price, availability) values (124, 'Micromax A88', 35, true);
insert into mobiles (id, model, price, availability) values (125, 'Micromax Selfie 2 Q4311', 71, false);
insert into mobiles (id, model, price, availability) values (126, 'Sony Ericsson Xperia X10 mini', 59, true);
insert into mobiles (id, model, price, availability) values (127, 'Wiko Fever 4G', 28, false);
insert into mobiles (id, model, price, availability) values (128, 'Celkon A105', 9, true);
insert into mobiles (id, model, price, availability) values (129, 'HTC Desire', 40, false);
insert into mobiles (id, model, price, availability) values (130, 'BlackBerry 7730', 31, false);
insert into mobiles (id, model, price, availability) values (131, 'Sony Ericsson K220', 87, true);
insert into mobiles (id, model, price, availability) values (132, 'LG Optimus G E970', 18, false);
insert into mobiles (id, model, price, availability) values (133, 'LG K4 (2017)', 35, false);
insert into mobiles (id, model, price, availability) values (134, 'LG Optimus L3 E400', 15, true);
insert into mobiles (id, model, price, availability) values (135, 'Siemens Xelibri 8', 3, false);
insert into mobiles (id, model, price, availability) values (136, 'Honor 8', 27, true);
insert into mobiles (id, model, price, availability) values (137, 'vivo NEX A', 85, false);
insert into mobiles (id, model, price, availability) values (138, 'Celkon A59', 12, true);
insert into mobiles (id, model, price, availability) values (139, 'Mitsubishi Trium Neptune', 36, false);
insert into mobiles (id, model, price, availability) values (140, 'Panasonic P66', 66, false);
insert into mobiles (id, model, price, availability) values (141, 'BLU Studio XL2', 65, true);
insert into mobiles (id, model, price, availability) values (142, 'Sony Xperia L4', 79, true);
insert into mobiles (id, model, price, availability) values (143, 'Lenovo M10 FHD REL', 1, true);
insert into mobiles (id, model, price, availability) values (144, 'Lenovo Golden Warrior Note 8', 58, true);
insert into mobiles (id, model, price, availability) values (145, 'Philips 530', 71, false);
insert into mobiles (id, model, price, availability) values (146, 'Wiko Kenny', 24, false);
insert into mobiles (id, model, price, availability) values (147, 'Samsung Galaxy S II LTE I9210', 34, true);
insert into mobiles (id, model, price, availability) values (148, 'ZTE Axon Lux', 83, true);
insert into mobiles (id, model, price, availability) values (149, 'Samsung E2330', 64, true);
insert into mobiles (id, model, price, availability) values (150, 'Samsung L870', 59, false);
insert into mobiles (id, model, price, availability) values (151, 'ZTE S302', 32, true);
insert into mobiles (id, model, price, availability) values (152, 'Palm Treo 650', 56, false);
insert into mobiles (id, model, price, availability) values (153, 'Huawei Enjoy 10s', 40, true);
insert into mobiles (id, model, price, availability) values (154, 'Sharp SH530U', 36, false);
insert into mobiles (id, model, price, availability) values (155, 'Xiaomi Mi Watch Lite', 31, true);
insert into mobiles (id, model, price, availability) values (156, 'QMobile Noir Z6', 88, true);
insert into mobiles (id, model, price, availability) values (157, 'Unnecto Quattro S', 98, false);
insert into mobiles (id, model, price, availability) values (158, 'Micromax Canvas 4 Plus A315', 99, false);
insert into mobiles (id, model, price, availability) values (159, 'Spice M-6868', 40, true);
insert into mobiles (id, model, price, availability) values (160, 'Motorola MILESTONE 2 ME722', 81, false);
insert into mobiles (id, model, price, availability) values (161, 'XOLO Era 1X', 98, false);
insert into mobiles (id, model, price, availability) values (162, 'HTC MAX 4G', 17, true);
insert into mobiles (id, model, price, availability) values (163, 'Coolpad Shine', 34, false);
insert into mobiles (id, model, price, availability) values (164, 'Apple Watch Edition 38mm (1st gen)', 63, false);
insert into mobiles (id, model, price, availability) values (165, 'Pantech PG-1900', 45, true);
insert into mobiles (id, model, price, availability) values (166, 'Sagem MY X6-2', 94, false);
insert into mobiles (id, model, price, availability) values (167, 'Spice Mi-353 Stellar Jazz', 52, true);
insert into mobiles (id, model, price, availability) values (168, 'HTC Desire 626 (USA)', 23, true);
insert into mobiles (id, model, price, availability) values (169, 'Sharp SE-02', 49, false);
insert into mobiles (id, model, price, availability) values (170, 'Cat S50', 43, true);
insert into mobiles (id, model, price, availability) values (171, 'Oppo A12s', 51, false);
insert into mobiles (id, model, price, availability) values (172, 'Samsung Galaxy Prevail 2', 36, false);
insert into mobiles (id, model, price, availability) values (173, 'alcatel Idol 3 (4.7)', 9, false);
insert into mobiles (id, model, price, availability) values (174, 'Samsung Gear S3 frontier LTE', 14, true);
insert into mobiles (id, model, price, availability) values (175, 'Xiaomi Mi Watch', 34, false);
insert into mobiles (id, model, price, availability) values (176, 'Maxon MX-V10', 3, false);
insert into mobiles (id, model, price, availability) values (177, 'O2 Xphone', 23, false);
insert into mobiles (id, model, price, availability) values (178, 'T-Mobile Vairy Touch II', 99, false);
insert into mobiles (id, model, price, availability) values (179, 'Xiaomi Mi 5c', 94, true);
insert into mobiles (id, model, price, availability) values (180, 'HTC One E9s dual sim', 58, true);
insert into mobiles (id, model, price, availability) values (181, 'Xiaomi Mi CC9 Pro', 47, true);
insert into mobiles (id, model, price, availability) values (182, 'alcatel Pop 7S', 66, false);
insert into mobiles (id, model, price, availability) values (183, 'Karbonn A12+', 6, false);
insert into mobiles (id, model, price, availability) values (184, 'OnePlus Nord N10 5G', 65, false);
insert into mobiles (id, model, price, availability) values (185, 'Samsung Galaxy Tab 3 10.1 P5220', 79, true);
insert into mobiles (id, model, price, availability) values (186, 'BenQ S670C', 40, true);
insert into mobiles (id, model, price, availability) values (187, 'Spice M 4580', 80, false);
insert into mobiles (id, model, price, availability) values (188, 'Siemens A70', 10, false);
insert into mobiles (id, model, price, availability) values (189, 'Samsung Guru Plus ', 6, true);
insert into mobiles (id, model, price, availability) values (190, 'Motorola MOTOKEY Mini EX108', 63, true);
insert into mobiles (id, model, price, availability) values (191, 'Parla Sonic 3.5S', 12, false);
insert into mobiles (id, model, price, availability) values (192, 'Samsung X520', 52, true);
insert into mobiles (id, model, price, availability) values (193, 'Samsung Galaxy 551', 10, true);
insert into mobiles (id, model, price, availability) values (194, 'Oppo A83', 86, true);
insert into mobiles (id, model, price, availability) values (195, 'Motorola RIZR Z10', 33, true);
insert into mobiles (id, model, price, availability) values (196, 'LG KM338', 94, false);
insert into mobiles (id, model, price, availability) values (197, 'Maxwest Orbit 6200T', 12, false);
insert into mobiles (id, model, price, availability) values (198, 'Microsoft Lumia 430 Dual SIM', 100, false);
insert into mobiles (id, model, price, availability) values (199, 'Intex Aqua Xtreme II', 56, true);
insert into mobiles (id, model, price, availability) values (200, 'alcatel OT-508A', 59, true);
insert into mobiles (id, model, price, availability) values (201, 'Xiaomi Mi Watch', 20, false);
insert into mobiles (id, model, price, availability) values (202, 'Sony Ericsson Z770', 25, false);
insert into mobiles (id, model, price, availability) values (203, 'Siemens C10', 5, false);
insert into mobiles (id, model, price, availability) values (204, 'Samsung M3710 Corby Beat', 96, false);
insert into mobiles (id, model, price, availability) values (205, 'Plum Pilot Plus', 28, true);
insert into mobiles (id, model, price, availability) values (206, 'vivo Y69', 87, true);
insert into mobiles (id, model, price, availability) values (207, 'Samsung Galaxy K zoom', 51, true);
insert into mobiles (id, model, price, availability) values (208, 'Tecno F2', 81, true);
insert into mobiles (id, model, price, availability) values (209, 'alcatel OT-S621', 91, true);
insert into mobiles (id, model, price, availability) values (210, 'Sony Ericsson K300', 35, true);
insert into mobiles (id, model, price, availability) values (211, 'Energizer Power Max P20', 52, true);
insert into mobiles (id, model, price, availability) values (212, 'vivo Y52s', 86, false);
insert into mobiles (id, model, price, availability) values (213, 'Xiaomi Redmi 4A', 97, true);
insert into mobiles (id, model, price, availability) values (214, 'Samsung SGH-800', 57, false);
insert into mobiles (id, model, price, availability) values (215, 'Panasonic Eluga I2 (2016)', 91, true);
insert into mobiles (id, model, price, availability) values (216, 'Oppo Reno4 F', 37, true);
insert into mobiles (id, model, price, availability) values (217, 'Huawei nova 5i', 93, true);
insert into mobiles (id, model, price, availability) values (218, 'Celkon Millennia Xplore', 32, false);
insert into mobiles (id, model, price, availability) values (219, 'BLU Studio G2 HD', 16, true);
insert into mobiles (id, model, price, availability) values (220, 'LG X4+', 89, true);
insert into mobiles (id, model, price, availability) values (221, 'Samsung Focus S I937', 71, true);
insert into mobiles (id, model, price, availability) values (222, 'Infinix Smart 4', 6, true);
insert into mobiles (id, model, price, availability) values (223, 'Karbonn A34', 61, true);
insert into mobiles (id, model, price, availability) values (224, 'Micromax A119 Canvas XL', 70, false);
insert into mobiles (id, model, price, availability) values (225, 'Realme Watch S Pro', 78, true);
insert into mobiles (id, model, price, availability) values (226, 'Sagem my301X', 79, true);
insert into mobiles (id, model, price, availability) values (227, 'ZTE Blade A7s 2020', 1, false);
insert into mobiles (id, model, price, availability) values (228, 'Samsung Galaxy Tab CDMA P100', 8, true);
insert into mobiles (id, model, price, availability) values (229, 'BLU Tattoo S', 37, true);
insert into mobiles (id, model, price, availability) values (230, 'Yezz Epic T7', 74, true);
insert into mobiles (id, model, price, availability) values (231, 'alcatel One Touch Snap LTE', 15, false);
insert into mobiles (id, model, price, availability) values (232, 'Samsung M5650 Lindy', 17, true);
insert into mobiles (id, model, price, availability) values (233, 'alcatel OT 835', 28, true);
insert into mobiles (id, model, price, availability) values (234, 'Unnecto Tap', 30, false);
insert into mobiles (id, model, price, availability) values (235, 'Motorola Timeport P7389', 10, true);
insert into mobiles (id, model, price, availability) values (236, 'Nokia 8800 Arte', 80, true);
insert into mobiles (id, model, price, availability) values (237, 'Acer Liquid M320', 41, true);
insert into mobiles (id, model, price, availability) values (238, 'Toshiba TG02', 53, true);
insert into mobiles (id, model, price, availability) values (239, 'QMobile Noir S9', 67, true);
insert into mobiles (id, model, price, availability) values (240, 'vivo Y20i', 74, false);
insert into mobiles (id, model, price, availability) values (241, 'Prestigio MultiPad 4 Ultimate 8.0 3G', 22, true);
insert into mobiles (id, model, price, availability) values (242, 'ZTE Grand S II S291', 18, false);
insert into mobiles (id, model, price, availability) values (243, 'Sony Xperia acro HD SO-03D', 99, false);
insert into mobiles (id, model, price, availability) values (244, 'alcatel OT Max db', 33, false);
insert into mobiles (id, model, price, availability) values (245, 'Lenovo A7-50 A3500', 40, false);
insert into mobiles (id, model, price, availability) values (246, 'Nokia C5 Endi', 27, false);
insert into mobiles (id, model, price, availability) values (247, 'vivo iQOO Neo 855', 47, true);
insert into mobiles (id, model, price, availability) values (248, 'alcatel OT 156', 96, false);
insert into mobiles (id, model, price, availability) values (249, 'Honor V6', 64, false);
insert into mobiles (id, model, price, availability) values (250, 'alcatel Idol 5s', 68, false);
insert into mobiles (id, model, price, availability) values (251, 'Mitac MIO 8870', 49, false);
insert into mobiles (id, model, price, availability) values (252, 'Tel.Me. T909', 55, true);
insert into mobiles (id, model, price, availability) values (253, 'Acer Liquid Z220', 68, true);
insert into mobiles (id, model, price, availability) values (254, 'Posh Volt Max LTE L640', 30, true);
insert into mobiles (id, model, price, availability) values (255, 'LG Optimus Pro C660', 38, false);
insert into mobiles (id, model, price, availability) values (256, 'Sony Xperia XA1 Plus', 33, false);
insert into mobiles (id, model, price, availability) values (257, 'Ericsson SH 888', 11, false);
insert into mobiles (id, model, price, availability) values (258, 'Huawei Enjoy 6', 65, false);
insert into mobiles (id, model, price, availability) values (259, 'Nokia 100', 8, false);
insert into mobiles (id, model, price, availability) values (260, 'LG G4', 78, false);
insert into mobiles (id, model, price, availability) values (261, 'Panasonic Eluga I3', 83, false);
insert into mobiles (id, model, price, availability) values (262, 'Nokia 9210i Communicator', 58, true);
insert into mobiles (id, model, price, availability) values (263, 'Motorola CUPE', 36, false);
insert into mobiles (id, model, price, availability) values (264, 'Samsung E2330', 42, true);
insert into mobiles (id, model, price, availability) values (265, 'Sendo S230', 73, false);
insert into mobiles (id, model, price, availability) values (266, 'Allview V4 Viper Pro', 55, true);
insert into mobiles (id, model, price, availability) values (267, 'alcatel OT-V212', 2, false);
insert into mobiles (id, model, price, availability) values (268, 'Samsung Galaxy Tab 7.7 LTE I815', 9, false);
insert into mobiles (id, model, price, availability) values (269, 'Samsung Galaxy C7 Pro', 11, false);
insert into mobiles (id, model, price, availability) values (270, 'Siemens A65', 83, false);
insert into mobiles (id, model, price, availability) values (271, 'Meizu V8 Pro', 88, true);
insert into mobiles (id, model, price, availability) values (272, 'Plum Gator', 3, false);
insert into mobiles (id, model, price, availability) values (273, 'Samsung Galaxy Round G910S', 87, true);
insert into mobiles (id, model, price, availability) values (274, 'Nokia C5-05', 92, false);
insert into mobiles (id, model, price, availability) values (275, 'alcatel Pop Fit', 2, true);
insert into mobiles (id, model, price, availability) values (276, 'Motorola P30', 15, true);
insert into mobiles (id, model, price, availability) values (277, 'Asus Zenfone Go ZB500KL', 71, false);
insert into mobiles (id, model, price, availability) values (278, 'Plum Buzz', 4, false);
insert into mobiles (id, model, price, availability) values (279, 'HTC Legend', 70, false);
insert into mobiles (id, model, price, availability) values (280, 'Sony Xperia GX SO-04D', 70, false);
insert into mobiles (id, model, price, availability) values (281, 'alcatel Pixi 3 (7) LTE', 41, false);
insert into mobiles (id, model, price, availability) values (282, 'LG C2600', 40, false);
insert into mobiles (id, model, price, availability) values (283, 'LG A7150', 81, false);
insert into mobiles (id, model, price, availability) values (284, 'Huawei Mate Xs', 54, false);
insert into mobiles (id, model, price, availability) values (285, 'i-mate Ultimate 8150', 54, true);
insert into mobiles (id, model, price, availability) values (286, 'Samsung Conquer 4G', 49, true);
insert into mobiles (id, model, price, availability) values (287, 'Motorola One Hyper', 41, true);
insert into mobiles (id, model, price, availability) values (288, 'Lava Iris 470', 97, true);
insert into mobiles (id, model, price, availability) values (289, 'Philips Xenium 9@98', 24, true);
insert into mobiles (id, model, price, availability) values (290, 'BLU Vivo XL3', 87, false);
insert into mobiles (id, model, price, availability) values (291, 'Motorola Moto G6 Plus', 100, true);
insert into mobiles (id, model, price, availability) values (292, 'T-Mobile G2x', 38, true);
insert into mobiles (id, model, price, availability) values (293, 'BlackBerry Tour 9630', 93, false);
insert into mobiles (id, model, price, availability) values (294, 'ZTE nubia Alpha', 89, false);
insert into mobiles (id, model, price, availability) values (295, 'BLU J6', 26, false);
insert into mobiles (id, model, price, availability) values (296, 'Dell XPS 10', 59, true);
insert into mobiles (id, model, price, availability) values (297, 'Nokia 6111', 60, false);
insert into mobiles (id, model, price, availability) values (298, 'ZTE Blade V7 Max', 2, false);
insert into mobiles (id, model, price, availability) values (299, 'HTC One M8 Prime', 79, true);
insert into mobiles (id, model, price, availability) values (300, 'Lenovo S650', 30, false);
insert into mobiles (id, model, price, availability) values (301, 'i-mate JAMA', 18, false);
insert into mobiles (id, model, price, availability) values (302, 'Plum Play', 44, false);
insert into mobiles (id, model, price, availability) values (303, 'Lava X46', 43, false);
insert into mobiles (id, model, price, availability) values (304, 'Samsung Galaxy Note FE', 83, true);
insert into mobiles (id, model, price, availability) values (305, 'Maxwest Astro 5s', 75, true);
insert into mobiles (id, model, price, availability) values (306, 'LG GD880 Mini', 18, false);
insert into mobiles (id, model, price, availability) values (307, 'Allview Viper E', 23, false);
insert into mobiles (id, model, price, availability) values (308, 'Gionee F5', 66, true);
insert into mobiles (id, model, price, availability) values (309, 'Philips 580', 83, false);
insert into mobiles (id, model, price, availability) values (310, 'Microsoft Lumia 540 Dual SIM', 95, true);
insert into mobiles (id, model, price, availability) values (311, 'XCute DV50', 46, true);
insert into mobiles (id, model, price, availability) values (312, 'alcatel OT-880 One Touch XTRA', 17, true);
insert into mobiles (id, model, price, availability) values (313, 'Nokia Asha 300', 38, false);
insert into mobiles (id, model, price, availability) values (314, 'Sony Ericsson J132', 93, false);
insert into mobiles (id, model, price, availability) values (315, 'Asus Fonepad 8 FE380CG', 79, false);
insert into mobiles (id, model, price, availability) values (316, 'Celkon CT-910', 99, true);
insert into mobiles (id, model, price, availability) values (317, 'Maxon MX-7920', 42, true);
insert into mobiles (id, model, price, availability) values (318, 'Samsung E1160', 7, false);
insert into mobiles (id, model, price, availability) values (319, 'Samsung T100', 37, true);
insert into mobiles (id, model, price, availability) values (320, 'Samsung E1170', 28, true);
insert into mobiles (id, model, price, availability) values (321, 'Spice Mi-353 Stellar Jazz', 1, false);
insert into mobiles (id, model, price, availability) values (322, 'Philips S616', 41, true);
insert into mobiles (id, model, price, availability) values (323, 'Micromax Funbook P300', 79, true);
insert into mobiles (id, model, price, availability) values (324, 'Huawei Ascend Q M5660', 27, true);
insert into mobiles (id, model, price, availability) values (325, 'Honor 8', 64, false);
insert into mobiles (id, model, price, availability) values (326, 'i-mate Pocket PC', 17, true);
insert into mobiles (id, model, price, availability) values (327, 'Vertu Ascent', 24, false);
insert into mobiles (id, model, price, availability) values (328, 'BLU G5 Plus', 73, false);
insert into mobiles (id, model, price, availability) values (329, 'Sagem my400X', 13, false);
insert into mobiles (id, model, price, availability) values (330, 'verykool s5007 Lotus Plus', 85, false);
insert into mobiles (id, model, price, availability) values (331, 'Sharp GX10i', 63, true);
insert into mobiles (id, model, price, availability) values (332, 'BenQ-Siemens C32', 95, false);
insert into mobiles (id, model, price, availability) values (333, 'Oppo Reno3 Youth', 80, true);
insert into mobiles (id, model, price, availability) values (334, 'Vodafone Smart V8', 40, false);
insert into mobiles (id, model, price, availability) values (335, 'BlackBerry 9720', 95, true);
insert into mobiles (id, model, price, availability) values (336, 'Motorola Talkabout T2288', 3, false);
insert into mobiles (id, model, price, availability) values (337, 'Samsung i900 Omnia', 4, false);
insert into mobiles (id, model, price, availability) values (338, 'Samsung Galaxy K zoom', 91, true);
insert into mobiles (id, model, price, availability) values (339, 'verykool s5526 Alpha', 10, false);
insert into mobiles (id, model, price, availability) values (340, 'HTC Touch Diamond CDMA', 4, true);
insert into mobiles (id, model, price, availability) values (341, 'Philips 855', 99, true);
insert into mobiles (id, model, price, availability) values (342, 'Celkon C66', 21, false);
insert into mobiles (id, model, price, availability) values (343, 'BenQ M100', 29, true);
insert into mobiles (id, model, price, availability) values (344, 'Huawei Ascend W1', 59, true);
insert into mobiles (id, model, price, availability) values (345, 'XOLO Omega 5.5', 25, false);
insert into mobiles (id, model, price, availability) values (346, 'Panasonic Eluga Ray Max', 40, true);
insert into mobiles (id, model, price, availability) values (347, 'Philips W920', 72, false);
insert into mobiles (id, model, price, availability) values (348, 'Wiko Sunny', 42, true);
insert into mobiles (id, model, price, availability) values (349, 'Nokia E6', 73, true);
insert into mobiles (id, model, price, availability) values (350, 'Acer Liquid Z630S', 3, true);
insert into mobiles (id, model, price, availability) values (351, 'Sony Xperia SP', 92, false);
insert into mobiles (id, model, price, availability) values (352, 'Samsung Galaxy S5 Neo', 85, true);
insert into mobiles (id, model, price, availability) values (353, 'Celkon C60', 31, true);
insert into mobiles (id, model, price, availability) values (354, 'Samsung Galaxy A42 5G', 8, false);
insert into mobiles (id, model, price, availability) values (355, 'Asus Zenfone Max (M1) ZB555KL', 73, true);
insert into mobiles (id, model, price, availability) values (356, 'Icemobile Submarine', 46, true);
insert into mobiles (id, model, price, availability) values (357, 'Samsung Galaxy Pocket plus S5301', 87, false);
insert into mobiles (id, model, price, availability) values (358, 'alcatel Pop C5', 44, true);
insert into mobiles (id, model, price, availability) values (359, 'Nokia 8', 66, false);
insert into mobiles (id, model, price, availability) values (360, 'Micromax A110Q Canvas 2 Plus', 28, true);
insert into mobiles (id, model, price, availability) values (361, 'Philips V726', 52, true);
insert into mobiles (id, model, price, availability) values (362, 'BLU Dash 5.0', 97, false);
insert into mobiles (id, model, price, availability) values (363, 'Celkon Campus Whizz Q42', 99, true);
insert into mobiles (id, model, price, availability) values (364, 'Nokia 5530 XpressMusic', 74, false);
insert into mobiles (id, model, price, availability) values (365, 'Vodafone Smart ultra 7', 11, true);
insert into mobiles (id, model, price, availability) values (366, 'LG G4', 49, false);
insert into mobiles (id, model, price, availability) values (367, 'Icemobile G10', 99, true);
insert into mobiles (id, model, price, availability) values (368, 'Motorola ATRIX HD MB886', 51, true);
insert into mobiles (id, model, price, availability) values (369, 'Samsung U300', 54, false);
insert into mobiles (id, model, price, availability) values (370, 'Sagem MC 959', 14, true);
insert into mobiles (id, model, price, availability) values (371, 'Micromax X55 Blade', 82, false);
insert into mobiles (id, model, price, availability) values (372, 'Huawei Ascend D1 XL U9500E', 23, true);
insert into mobiles (id, model, price, availability) values (373, 'XOLO Black', 68, true);
insert into mobiles (id, model, price, availability) values (374, 'Bosch Com 608', 26, true);
insert into mobiles (id, model, price, availability) values (375, 'Lenovo A6000 Plus', 99, true);
insert into mobiles (id, model, price, availability) values (376, 'Philips Xenium 9@9k', 82, true);
insert into mobiles (id, model, price, availability) values (377, 'Samsung Z600', 95, false);
insert into mobiles (id, model, price, availability) values (378, 'Huawei Enjoy 10', 35, false);
insert into mobiles (id, model, price, availability) values (379, 'Spice S-5420', 94, false);
insert into mobiles (id, model, price, availability) values (380, 'Samsung Galaxy M30', 36, false);
insert into mobiles (id, model, price, availability) values (381, 'Maxwest Astro 4', 78, false);
insert into mobiles (id, model, price, availability) values (382, 'Xiaomi Poco M2', 46, false);
insert into mobiles (id, model, price, availability) values (383, 'Motorola Karma QA1', 59, false);
insert into mobiles (id, model, price, availability) values (384, 'Nokia Lumia 610', 3, false);
insert into mobiles (id, model, price, availability) values (385, 'YU Yunicorn', 92, false);
insert into mobiles (id, model, price, availability) values (386, 'HTC Rezound', 69, false);
insert into mobiles (id, model, price, availability) values (387, 'Samsung Galaxy Tab 4 10.1 LTE', 25, true);
insert into mobiles (id, model, price, availability) values (388, 'Samsung C3212', 93, true);
insert into mobiles (id, model, price, availability) values (389, 'BLU Dash 4.0', 27, true);
insert into mobiles (id, model, price, availability) values (390, 'Xiaomi Mi Max', 3, true);
insert into mobiles (id, model, price, availability) values (391, 'Sony Ericsson Aino', 21, true);
insert into mobiles (id, model, price, availability) values (392, 'Pantech Jest II', 14, true);
insert into mobiles (id, model, price, availability) values (393, 'Samsung C520', 94, true);
insert into mobiles (id, model, price, availability) values (394, 'Modu Sport jacket', 66, false);
insert into mobiles (id, model, price, availability) values (395, 'Samsung X600', 50, false);
insert into mobiles (id, model, price, availability) values (396, 'Gigabyte GSmart Alto A2', 9, false);
insert into mobiles (id, model, price, availability) values (397, 'Micromax Vdeo 4', 77, true);
insert into mobiles (id, model, price, availability) values (398, 'Huawei Ascend W3', 55, false);
insert into mobiles (id, model, price, availability) values (399, 'LG V30S ThinQ', 44, false);
insert into mobiles (id, model, price, availability) values (400, 'LG Fireweb', 69, true);
insert into mobiles (id, model, price, availability) values (401, 'LG KP235', 40, true);
insert into mobiles (id, model, price, availability) values (402, 'Telit t800', 81, true);
insert into mobiles (id, model, price, availability) values (403, 'Lenovo S856', 36, false);
insert into mobiles (id, model, price, availability) values (404, 'Vodafone Smart X9', 39, false);
insert into mobiles (id, model, price, availability) values (405, 'Samsung B3410W Ch@t', 64, true);
insert into mobiles (id, model, price, availability) values (406, 'Sharp 934SH', 30, false);
insert into mobiles (id, model, price, availability) values (407, 'Nokia N97 mini', 55, false);
insert into mobiles (id, model, price, availability) values (408, 'Bird S698', 17, true);
insert into mobiles (id, model, price, availability) values (409, 'Gigabyte GSmart Guru', 39, true);
insert into mobiles (id, model, price, availability) values (410, 'Palm Treo 650', 39, false);
insert into mobiles (id, model, price, availability) values (411, 'Celkon A107', 100, true);
insert into mobiles (id, model, price, availability) values (412, 'Asus Zenfone Max ZC550KL', 48, false);
insert into mobiles (id, model, price, availability) values (413, 'HTC Desire 616 dual sim', 37, true);
insert into mobiles (id, model, price, availability) values (414, 'Asus Fonepad 7 (2014)', 97, true);
insert into mobiles (id, model, price, availability) values (415, 'Panasonic MX6', 38, true);
insert into mobiles (id, model, price, availability) values (416, 'Oppo R9s', 25, true);
insert into mobiles (id, model, price, availability) values (417, 'Lava Iris X1 Atom S', 45, false);
insert into mobiles (id, model, price, availability) values (418, 'Archos 45c Platinum', 93, false);
insert into mobiles (id, model, price, availability) values (419, 'BLU J7L', 4, false);
insert into mobiles (id, model, price, availability) values (420, 'LG KG330', 63, true);
insert into mobiles (id, model, price, availability) values (421, 'Philips Xenium X713', 30, false);
insert into mobiles (id, model, price, availability) values (422, 'Allview P6 Quad Plus', 11, false);
insert into mobiles (id, model, price, availability) values (423, 'Yezz Andy 3G 2.8 YZ11', 15, false);
insert into mobiles (id, model, price, availability) values (424, 'Haier V6000', 24, true);
insert into mobiles (id, model, price, availability) values (425, 'Micromax Q75', 83, true);
insert into mobiles (id, model, price, availability) values (426, 'Vodafone Smart 4G', 41, false);
insert into mobiles (id, model, price, availability) values (427, 'Huawei U8220', 20, false);
insert into mobiles (id, model, price, availability) values (428, 'Apple iPhone 7 Plus', 60, false);
insert into mobiles (id, model, price, availability) values (429, 'BLU Studio 7.0 LTE', 33, true);
insert into mobiles (id, model, price, availability) values (430, 'WND Wind DUO 2100', 3, false);
insert into mobiles (id, model, price, availability) values (431, 'XOLO A1010', 56, false);
insert into mobiles (id, model, price, availability) values (432, 'Archos 50 Graphite', 42, true);
insert into mobiles (id, model, price, availability) values (433, 'vivo iQOO U1', 61, false);
insert into mobiles (id, model, price, availability) values (434, 'Samsung T459 Gravity', 3, false);
insert into mobiles (id, model, price, availability) values (435, 'Nokia X2-02', 18, true);
insert into mobiles (id, model, price, availability) values (436, 'Sagem MC 940', 76, false);
insert into mobiles (id, model, price, availability) values (437, 'Acer Liquid Gallant Duo', 53, true);
insert into mobiles (id, model, price, availability) values (438, 'verykool s505', 91, false);
insert into mobiles (id, model, price, availability) values (439, 'QMobile Noir S1', 81, true);
insert into mobiles (id, model, price, availability) values (440, 'Motorola Moto E', 72, true);
insert into mobiles (id, model, price, availability) values (441, 'Qtek 9600', 60, true);
insert into mobiles (id, model, price, availability) values (442, 'BlackBerry Torch 9850', 27, true);
insert into mobiles (id, model, price, availability) values (443, 'O2 XDA mini S', 22, false);
insert into mobiles (id, model, price, availability) values (444, 'Karbonn K440', 29, false);
insert into mobiles (id, model, price, availability) values (445, 'Allview P7 Pro', 79, false);
insert into mobiles (id, model, price, availability) values (446, 'BenQ E53', 65, true);
insert into mobiles (id, model, price, availability) values (447, 'Nokia 130 (2017)', 19, false);
insert into mobiles (id, model, price, availability) values (448, 'Samsung Galaxy Tab 2 7.0 P3110', 5, true);
insert into mobiles (id, model, price, availability) values (449, 'Micromax Canvas Infinity Life', 36, false);
insert into mobiles (id, model, price, availability) values (450, 'Huawei MediaPad S7-301w', 8, true);
insert into mobiles (id, model, price, availability) values (451, 'Samsung I9506 Galaxy S4', 79, false);
insert into mobiles (id, model, price, availability) values (452, 'Gionee Pioneer P5W', 95, false);
insert into mobiles (id, model, price, availability) values (453, 'Motorola Moto G Dual SIM (3rd gen)', 60, true);
insert into mobiles (id, model, price, availability) values (454, 'Nokia 1800', 55, true);
insert into mobiles (id, model, price, availability) values (455, 'Acer Iconia Tab A101', 74, false);
insert into mobiles (id, model, price, availability) values (456, 'Nokia 3610', 61, false);
insert into mobiles (id, model, price, availability) values (457, 'BenQ-Siemens EF61', 56, false);
insert into mobiles (id, model, price, availability) values (458, 'Innostream INNO 78', 98, false);
insert into mobiles (id, model, price, availability) values (459, 'Siemens S10', 82, true);
insert into mobiles (id, model, price, availability) values (460, 'LG GT950 Arena', 9, false);
insert into mobiles (id, model, price, availability) values (461, 'Sony Ericsson W890', 100, true);
insert into mobiles (id, model, price, availability) values (462, 'Micromax A63 Canvas Fun', 46, false);
insert into mobiles (id, model, price, availability) values (463, 'Panasonic P77', 42, true);
insert into mobiles (id, model, price, availability) values (464, 'Samsung B2700', 73, true);
insert into mobiles (id, model, price, availability) values (465, 'LG KM570 Cookie Gig', 54, true);
insert into mobiles (id, model, price, availability) values (466, 'Sharp TM100', 94, true);
insert into mobiles (id, model, price, availability) values (467, 'verykool i674', 52, false);
insert into mobiles (id, model, price, availability) values (468, 'Yezz Andy 3.5EI2', 77, false);
insert into mobiles (id, model, price, availability) values (469, 'Nokia X1-00', 89, true);
insert into mobiles (id, model, price, availability) values (470, 'Karbonn K101+ Media Champ', 63, false);
insert into mobiles (id, model, price, availability) values (471, 'ZTE V9', 37, true);
insert into mobiles (id, model, price, availability) values (472, 'Wiko Selfy 4G', 41, true);
insert into mobiles (id, model, price, availability) values (473, 'Samsung B5722', 43, false);
insert into mobiles (id, model, price, availability) values (474, 'verykool R80', 43, false);
insert into mobiles (id, model, price, availability) values (475, 'Honor 9X Pro', 60, false);
insert into mobiles (id, model, price, availability) values (476, 'Huawei P40 lite', 4, true);
insert into mobiles (id, model, price, availability) values (477, 'Allview E3 Sign', 46, true);
insert into mobiles (id, model, price, availability) values (478, 'Oppo F5 Youth', 98, false);
insert into mobiles (id, model, price, availability) values (479, 'HTC Desire Eye', 100, false);
insert into mobiles (id, model, price, availability) values (480, 'Samsung B3410W Ch@t', 36, false);
insert into mobiles (id, model, price, availability) values (481, 'Haier M300', 23, true);
insert into mobiles (id, model, price, availability) values (482, 'HP Slate 17', 67, true);
insert into mobiles (id, model, price, availability) values (483, 'Icemobile Comet II', 93, true);
insert into mobiles (id, model, price, availability) values (484, 'Samsung Galaxy J1 4G', 59, true);
insert into mobiles (id, model, price, availability) values (485, 'Lenovo Tab M7', 81, false);
insert into mobiles (id, model, price, availability) values (486, 'Samsung C300', 32, false);
insert into mobiles (id, model, price, availability) values (487, 'Philips S616', 29, false);
insert into mobiles (id, model, price, availability) values (488, 'alcatel Shine Lite', 62, true);
insert into mobiles (id, model, price, availability) values (489, 'HTC One (M8) for Windows (CDMA)', 55, false);
insert into mobiles (id, model, price, availability) values (490, 'LG Optimus 3D Max P720', 55, false);
insert into mobiles (id, model, price, availability) values (491, 'Oppo A93 5G', 69, false);
insert into mobiles (id, model, price, availability) values (492, 'LG KF510', 27, false);
insert into mobiles (id, model, price, availability) values (493, 'HTC Wildfire R70', 92, false);
insert into mobiles (id, model, price, availability) values (494, 'MWg Atom V', 89, false);
insert into mobiles (id, model, price, availability) values (495, 'Philips 399', 51, true);
insert into mobiles (id, model, price, availability) values (496, 'Samsung T349', 56, true);
insert into mobiles (id, model, price, availability) values (497, 'ZTE nubia Z5', 25, false);
insert into mobiles (id, model, price, availability) values (498, 'Amoi CS6', 40, false);
insert into mobiles (id, model, price, availability) values (499, 'Huawei MediaPad X1', 11, false);
insert into mobiles (id, model, price, availability) values (500, 'Panasonic Eluga I', 82, true);
insert into mobiles (id, model, price, availability) values (501, 'Nvidia Shield K1', 90, false);
insert into mobiles (id, model, price, availability) values (502, 'Tecno Spark Pro', 16, true);
insert into mobiles (id, model, price, availability) values (503, 'alcatel OT-902', 50, false);
insert into mobiles (id, model, price, availability) values (504, 'Yezz Classic C50', 56, false);
insert into mobiles (id, model, price, availability) values (505, 'Asus Transformer Prime TF201', 25, true);
insert into mobiles (id, model, price, availability) values (506, 'BLU Dash 4.5 (2016)', 11, true);
insert into mobiles (id, model, price, availability) values (507, 'ZTE Blade V10', 83, false);
insert into mobiles (id, model, price, availability) values (508, 'Asus Transformer Book Trio', 27, true);
insert into mobiles (id, model, price, availability) values (509, 'Samsung i780', 49, false);
insert into mobiles (id, model, price, availability) values (510, 'Samsung Z1', 16, false);
insert into mobiles (id, model, price, availability) values (511, 'Lava A67', 91, true);
insert into mobiles (id, model, price, availability) values (512, 'BlackBerry Pearl 8110', 50, true);
insert into mobiles (id, model, price, availability) values (513, 'Motorola V186', 44, false);
insert into mobiles (id, model, price, availability) values (514, 'Samsung Galaxy J2 Prime', 8, false);
insert into mobiles (id, model, price, availability) values (515, 'Allview Viper i V1', 46, true);
insert into mobiles (id, model, price, availability) values (516, 'Samsung S5250 Wave525', 47, true);
insert into mobiles (id, model, price, availability) values (517, 'LG Optimus Vu F100S', 65, true);
insert into mobiles (id, model, price, availability) values (518, 'Samsung L310', 34, false);
insert into mobiles (id, model, price, availability) values (519, 'LG Optimus 4G LTE P935', 63, false);
insert into mobiles (id, model, price, availability) values (520, 'Samsung X830', 62, false);
insert into mobiles (id, model, price, availability) values (521, 'Samsung C5510', 54, true);
insert into mobiles (id, model, price, availability) values (522, 'Micromax A089 Bolt', 21, false);
insert into mobiles (id, model, price, availability) values (523, 'verykool s5015 Spark II', 95, true);
insert into mobiles (id, model, price, availability) values (524, 'alcatel Pixi 4 Plus Power', 81, false);
insert into mobiles (id, model, price, availability) values (525, 'alcatel OT COM', 93, true);
insert into mobiles (id, model, price, availability) values (526, 'Energizer Hardcase H280S', 71, true);
insert into mobiles (id, model, price, availability) values (527, 'Huawei Y9 (2018)', 79, false);
insert into mobiles (id, model, price, availability) values (528, 'Motorola ATRIX HD MB886', 67, true);
insert into mobiles (id, model, price, availability) values (529, 'HTC Explorer', 77, true);
insert into mobiles (id, model, price, availability) values (530, 'Philips Xenium 9@9v', 11, false);
insert into mobiles (id, model, price, availability) values (531, 'Celkon C74', 6, false);
insert into mobiles (id, model, price, availability) values (532, 'LG GB250', 83, true);
insert into mobiles (id, model, price, availability) values (533, 'Dell XCD35', 41, false);
insert into mobiles (id, model, price, availability) values (534, 'Huawei MatePad Pro 10.8 (2019)', 32, true);
insert into mobiles (id, model, price, availability) values (535, 'Samsung S7330', 75, true);
insert into mobiles (id, model, price, availability) values (536, 'LG C299', 19, false);
insert into mobiles (id, model, price, availability) values (537, 'ZTE PF112 HD', 41, true);
insert into mobiles (id, model, price, availability) values (538, 'Allview X4 Soul Infinity Z', 35, false);
insert into mobiles (id, model, price, availability) values (539, 'BLU Vivo 5R', 6, false);
insert into mobiles (id, model, price, availability) values (540, 'Apple iPhone 6 Plus', 12, false);
insert into mobiles (id, model, price, availability) values (541, 'Samsung Corby TV F339', 78, false);
insert into mobiles (id, model, price, availability) values (542, 'QMobile Noir X550', 59, false);
insert into mobiles (id, model, price, availability) values (543, 'Sharp 802', 18, true);
insert into mobiles (id, model, price, availability) values (544, 'i-mate SP5m', 93, false);
insert into mobiles (id, model, price, availability) values (545, 'Nokia 7600', 20, false);
insert into mobiles (id, model, price, availability) values (546, 'LG S5100', 70, false);
insert into mobiles (id, model, price, availability) values (547, 'LG Q6', 37, false);
insert into mobiles (id, model, price, availability) values (548, 'Samsung S100', 31, false);
insert into mobiles (id, model, price, availability) values (549, 'Benefon Esc!', 69, false);
insert into mobiles (id, model, price, availability) values (550, 'LG G7100', 33, true);
insert into mobiles (id, model, price, availability) values (551, 'Infinix Hot 4 Pro', 26, true);
insert into mobiles (id, model, price, availability) values (552, 'Lenovo S920', 16, true);
insert into mobiles (id, model, price, availability) values (553, 'Coolpad Note 6', 73, true);
insert into mobiles (id, model, price, availability) values (554, 'ZTE Axon 20 5G Extreme', 93, false);
insert into mobiles (id, model, price, availability) values (555, 'HTC Desire HD2', 66, false);
insert into mobiles (id, model, price, availability) values (556, 'Toshiba Thrive', 69, false);
insert into mobiles (id, model, price, availability) values (557, 'Philips 636', 81, true);
insert into mobiles (id, model, price, availability) values (558, 'Yezz Andy A5', 4, false);
insert into mobiles (id, model, price, availability) values (559, 'Amoi H810', 31, false);
insert into mobiles (id, model, price, availability) values (560, 'Apple Watch Series 6', 56, false);
insert into mobiles (id, model, price, availability) values (561, 'XOLO Play', 89, false);
insert into mobiles (id, model, price, availability) values (562, 'Apple iPad Wi-Fi', 79, false);
insert into mobiles (id, model, price, availability) values (563, 'Nokia E71', 31, true);
insert into mobiles (id, model, price, availability) values (564, 'Micromax Funbook 3G P560', 57, true);
insert into mobiles (id, model, price, availability) values (565, 'Samsung Z370', 80, true);
insert into mobiles (id, model, price, availability) values (566, 'Telit G90', 98, false);
insert into mobiles (id, model, price, availability) values (567, 'Qtek 8010', 60, false);
insert into mobiles (id, model, price, availability) values (568, 'Nokia C2-03', 43, false);
insert into mobiles (id, model, price, availability) values (569, 'alcatel Pixi 7', 77, true);
insert into mobiles (id, model, price, availability) values (570, 'Xiaomi Redmi 3s', 96, false);
insert into mobiles (id, model, price, availability) values (571, 'Tecno Pop 1', 74, false);
insert into mobiles (id, model, price, availability) values (572, 'Realme V5 5G', 53, true);
insert into mobiles (id, model, price, availability) values (573, 'Lenovo A916', 27, false);
insert into mobiles (id, model, price, availability) values (574, 'Samsung Galaxy Tab 3 7.0 WiFi', 47, true);
insert into mobiles (id, model, price, availability) values (575, 'Yezz Andy 5M LTE', 41, false);
insert into mobiles (id, model, price, availability) values (576, 'Acer beTouch E400', 31, true);
insert into mobiles (id, model, price, availability) values (577, 'LG SU920', 13, false);
insert into mobiles (id, model, price, availability) values (578, 'LG GB210', 39, false);
insert into mobiles (id, model, price, availability) values (579, 'Samsung Galaxy Core Lite LTE', 48, false);
insert into mobiles (id, model, price, availability) values (580, 'Micromax Bolt Q339', 75, true);
insert into mobiles (id, model, price, availability) values (581, 'Samsung U750 Zeal', 45, false);
insert into mobiles (id, model, price, availability) values (582, 'Panasonic Eluga I7', 68, true);
insert into mobiles (id, model, price, availability) values (583, 'Google Pixel', 37, false);
insert into mobiles (id, model, price, availability) values (584, 'LG Optimus L2 II E435', 9, false);
insert into mobiles (id, model, price, availability) values (585, 'Allview P7 Pro', 24, false);
insert into mobiles (id, model, price, availability) values (586, 'Nokia 2680 slide', 13, true);
insert into mobiles (id, model, price, availability) values (587, 'ZTE Blade G Lux', 56, true);
insert into mobiles (id, model, price, availability) values (588, 'ZTE Light Tab V9C', 99, false);
insert into mobiles (id, model, price, availability) values (589, 'LG K8 (2017)', 100, true);
insert into mobiles (id, model, price, availability) values (590, 'Plum Stubby II', 15, false);
insert into mobiles (id, model, price, availability) values (591, 'Samsung E105', 12, true);
insert into mobiles (id, model, price, availability) values (592, 'LG US760 Genesis', 4, false);
insert into mobiles (id, model, price, availability) values (593, 'Kyocera Hydro Elite', 66, true);
insert into mobiles (id, model, price, availability) values (594, 'LeEco Le Pro3 Elite', 31, true);
insert into mobiles (id, model, price, availability) values (595, 'Sony Ericsson P1', 19, false);
insert into mobiles (id, model, price, availability) values (596, 'Samsung S200', 11, true);
insert into mobiles (id, model, price, availability) values (597, 'Philips X500', 60, false);
insert into mobiles (id, model, price, availability) values (598, 'LG Tribute Empire', 50, false);
insert into mobiles (id, model, price, availability) values (599, 'Allview P6 Pro', 2, false);
insert into mobiles (id, model, price, availability) values (600, 'Infinix Smart', 1, false);
insert into mobiles (id, model, price, availability) values (601, 'vivo V15 Pro', 40, true);
insert into mobiles (id, model, price, availability) values (602, 'Plum Flipper', 49, false);
insert into mobiles (id, model, price, availability) values (603, 'Gigabyte GSmart i120', 64, false);
insert into mobiles (id, model, price, availability) values (604, 'Infinix Hot S3', 30, false);
insert into mobiles (id, model, price, availability) values (605, 'vivo Y91', 35, true);
insert into mobiles (id, model, price, availability) values (606, 'Google Pixel C', 51, false);
insert into mobiles (id, model, price, availability) values (607, 'Celkon C509', 17, false);
insert into mobiles (id, model, price, availability) values (608, 'Icemobile Prime 3.5', 85, true);
insert into mobiles (id, model, price, availability) values (609, 'Samsung Galaxy S10 5G', 30, true);
insert into mobiles (id, model, price, availability) values (610, 'Ericsson S 868', 27, false);
insert into mobiles (id, model, price, availability) values (611, 'BLU Dash L5 LTE', 60, true);
insert into mobiles (id, model, price, availability) values (612, 'Motorola Moto G5S Plus', 5, true);
insert into mobiles (id, model, price, availability) values (613, 'Xiaomi Redmi 3s Prime', 82, false);
insert into mobiles (id, model, price, availability) values (614, 'Lenovo Vibe X3', 85, false);
insert into mobiles (id, model, price, availability) values (615, 'Icemobile Apollo Touch', 47, true);
insert into mobiles (id, model, price, availability) values (616, 'alcatel Pop 2 (4.5) Dual SIM', 9, false);
insert into mobiles (id, model, price, availability) values (617, 'Intex IRist Smartwatch', 28, true);
insert into mobiles (id, model, price, availability) values (618, 'Asus Zenfone 4 Selfie ZB553KL', 17, false);
insert into mobiles (id, model, price, availability) values (619, 'Ulefone Armor 10 5G', 92, true);
insert into mobiles (id, model, price, availability) values (620, 'Nokia 2760', 91, false);
insert into mobiles (id, model, price, availability) values (621, 'Samsung S5330 Wave533', 16, true);
insert into mobiles (id, model, price, availability) values (622, 'Huawei Y9 Prime (2019)', 9, true);
insert into mobiles (id, model, price, availability) values (623, 'BLU Dash', 99, false);
insert into mobiles (id, model, price, availability) values (624, 'BLU Win HD LTE', 61, false);
insert into mobiles (id, model, price, availability) values (625, 'Nokia 8910', 42, true);
insert into mobiles (id, model, price, availability) values (626, 'Celkon A35k', 78, false);
insert into mobiles (id, model, price, availability) values (627, 'BLU Studio M LTE', 6, false);
insert into mobiles (id, model, price, availability) values (628, 'Vodafone 1240', 48, false);
insert into mobiles (id, model, price, availability) values (629, 'Motorola V188', 40, true);
insert into mobiles (id, model, price, availability) values (630, 'Honor V30', 100, false);
insert into mobiles (id, model, price, availability) values (631, 'Sony Ericsson Z250', 14, true);
insert into mobiles (id, model, price, availability) values (632, 'Huawei Ascend D2', 44, false);
insert into mobiles (id, model, price, availability) values (633, 'Panasonic X800', 97, true);
insert into mobiles (id, model, price, availability) values (634, 'Sony Xperia T3', 71, false);
insert into mobiles (id, model, price, availability) values (635, 'verykool s758', 16, true);
insert into mobiles (id, model, price, availability) values (636, 'Asus Google Nexus 7 (2013)', 21, false);
insert into mobiles (id, model, price, availability) values (637, 'Samsung E100', 48, true);
insert into mobiles (id, model, price, availability) values (638, 'Sony Ericsson Xperia active', 26, false);
insert into mobiles (id, model, price, availability) values (639, 'LG U8380', 74, false);
insert into mobiles (id, model, price, availability) values (640, 'Apple iPhone 5', 85, false);
insert into mobiles (id, model, price, availability) values (641, 'Sony Ericsson V640', 59, true);
insert into mobiles (id, model, price, availability) values (642, 'Sony Xperia E1', 53, false);
insert into mobiles (id, model, price, availability) values (643, 'ZTE nubia M2 lite', 79, true);
insert into mobiles (id, model, price, availability) values (644, 'NEC e1108', 72, false);
insert into mobiles (id, model, price, availability) values (645, 'Philips 290', 28, true);
insert into mobiles (id, model, price, availability) values (646, 'Honor Play 8A', 12, false);
insert into mobiles (id, model, price, availability) values (647, 'LG Optimus F6', 48, true);
insert into mobiles (id, model, price, availability) values (648, 'Samsung Galaxy Tab 4 10.1 LTE', 92, false);
insert into mobiles (id, model, price, availability) values (649, 'Micromax A87 Ninja 4.0', 90, true);
insert into mobiles (id, model, price, availability) values (650, 'i-mate Ultimate 8150', 84, false);
insert into mobiles (id, model, price, availability) values (651, 'Philips X125', 90, false);
insert into mobiles (id, model, price, availability) values (652, 'Archos 50 Graphite', 79, true);
insert into mobiles (id, model, price, availability) values (653, 'Motorola V191', 59, false);
insert into mobiles (id, model, price, availability) values (654, 'Gionee F103 Pro', 71, true);
insert into mobiles (id, model, price, availability) values (655, 'LG KG270', 19, true);
insert into mobiles (id, model, price, availability) values (656, 'Huawei Ascend P7', 40, true);
insert into mobiles (id, model, price, availability) values (657, 'Allview X2 Soul Style', 1, false);
insert into mobiles (id, model, price, availability) values (658, 'Samsung C275', 2, true);
insert into mobiles (id, model, price, availability) values (659, 'Neonode N1m', 83, false);
insert into mobiles (id, model, price, availability) values (660, 'Philips Xenium F511', 11, true);
insert into mobiles (id, model, price, availability) values (661, 'Samsung A127', 49, true);
insert into mobiles (id, model, price, availability) values (662, 'Energizer Hardcase H240S', 85, false);
insert into mobiles (id, model, price, availability) values (663, 'Huawei Ascend G6', 1, false);
insert into mobiles (id, model, price, availability) values (664, 'LG Optimus Net', 13, false);
insert into mobiles (id, model, price, availability) values (665, 'Huawei Mate 10 Porsche Design', 72, false);
insert into mobiles (id, model, price, availability) values (666, 'Lenovo A7', 100, false);
insert into mobiles (id, model, price, availability) values (667, 'Oppo U3', 46, true);
insert into mobiles (id, model, price, availability) values (668, 'Gigabyte GSmart G1342 Houston', 20, true);
insert into mobiles (id, model, price, availability) values (669, 'BLU R2', 91, true);
insert into mobiles (id, model, price, availability) values (670, 'Sagem my200C', 37, false);
insert into mobiles (id, model, price, availability) values (671, 'Karbonn A15', 34, true);
insert into mobiles (id, model, price, availability) values (672, 'Motorola V600', 48, false);
insert into mobiles (id, model, price, availability) values (673, 'XOLO Win Q900s', 20, false);
insert into mobiles (id, model, price, availability) values (674, 'Nokia 5300', 88, false);
insert into mobiles (id, model, price, availability) values (675, 'Gionee Marathon M5 Plus', 77, false);
insert into mobiles (id, model, price, availability) values (676, 'Samsung Galaxy A9 (2016)', 1, true);
insert into mobiles (id, model, price, availability) values (677, 'Huawei U1100', 13, false);
insert into mobiles (id, model, price, availability) values (678, 'Plum Flipper', 75, true);
insert into mobiles (id, model, price, availability) values (679, 'BLU Studio 5.5 S', 24, false);
insert into mobiles (id, model, price, availability) values (680, 'BLU Cubo', 35, false);
insert into mobiles (id, model, price, availability) values (681, 'Haier A66', 6, true);
insert into mobiles (id, model, price, availability) values (682, 'Vertu Ascent', 87, false);
insert into mobiles (id, model, price, availability) values (683, 'Oppo F15', 78, true);
insert into mobiles (id, model, price, availability) values (684, 'alcatel Idol 4s', 2, false);
insert into mobiles (id, model, price, availability) values (685, 'Huawei MediaPad M3 Lite 8', 4, true);
insert into mobiles (id, model, price, availability) values (686, 'BenQ-Siemens SF71', 77, false);
insert into mobiles (id, model, price, availability) values (687, 'Lenovo Z5', 98, true);
insert into mobiles (id, model, price, availability) values (688, 'Sony Ericsson W900', 63, false);
insert into mobiles (id, model, price, availability) values (689, 'Nokia 6150', 90, true);
insert into mobiles (id, model, price, availability) values (690, 'BlackBerry 7100x', 94, false);
insert into mobiles (id, model, price, availability) values (691, 'Huawei Y7 Pro (2018)', 8, true);
insert into mobiles (id, model, price, availability) values (692, 'Modu Express jacket', 63, true);
insert into mobiles (id, model, price, availability) values (693, 'Sony Ericsson V630', 62, true);
insert into mobiles (id, model, price, availability) values (694, 'Sony Ericsson J220', 77, true);
insert into mobiles (id, model, price, availability) values (695, 'NEC 804N', 42, true);
insert into mobiles (id, model, price, availability) values (696, 'Gionee Pioneer P5L', 53, true);
insert into mobiles (id, model, price, availability) values (697, 'Motorola MT810lx', 19, false);
insert into mobiles (id, model, price, availability) values (698, 'Samsung Galaxy J3 (2017)', 36, false);
insert into mobiles (id, model, price, availability) values (699, 'T-Mobile G2', 6, true);
insert into mobiles (id, model, price, availability) values (700, 'Micromax Canvas Tab P690', 22, false);
insert into mobiles (id, model, price, availability) values (701, 'Samsung :) Smiley', 96, true);
insert into mobiles (id, model, price, availability) values (702, 'Sony Ericsson W715', 90, true);
insert into mobiles (id, model, price, availability) values (703, 'verykool i270', 51, false);
insert into mobiles (id, model, price, availability) values (704, 'Motorola Razr 5G', 96, true);
insert into mobiles (id, model, price, availability) values (705, 'BLU Grand M2 (2018)', 16, false);
insert into mobiles (id, model, price, availability) values (706, 'Motorola XOOM MZ600', 99, false);
insert into mobiles (id, model, price, availability) values (707, 'T-Mobile Vairy Touch', 1, true);
insert into mobiles (id, model, price, availability) values (708, 'Honor 20S', 79, false);
insert into mobiles (id, model, price, availability) values (709, 'Vodafone Smart Mini', 61, true);
insert into mobiles (id, model, price, availability) values (710, 'Motorola RIZR Z3', 81, false);
insert into mobiles (id, model, price, availability) values (711, 'Acer beTouch E120', 23, true);
insert into mobiles (id, model, price, availability) values (712, 'Micromax Q50', 47, true);
insert into mobiles (id, model, price, availability) values (713, 'Samsung I5700 Galaxy Spica', 100, true);
insert into mobiles (id, model, price, availability) values (714, 'Lenovo Tab S8', 26, true);
insert into mobiles (id, model, price, availability) values (715, 'Oppo Reno3 Pro 5G', 21, false);
insert into mobiles (id, model, price, availability) values (716, 'Huawei nova 5i', 71, true);
insert into mobiles (id, model, price, availability) values (717, 'Nokia 216', 58, true);
insert into mobiles (id, model, price, availability) values (718, 'BenQ T33', 92, true);
insert into mobiles (id, model, price, availability) values (719, 'alcatel OT 531', 98, false);
insert into mobiles (id, model, price, availability) values (720, 'Huawei Y5p', 32, false);
insert into mobiles (id, model, price, availability) values (721, 'LG Esteem MS910', 35, true);
insert into mobiles (id, model, price, availability) values (722, 'Celkon C769', 17, false);
insert into mobiles (id, model, price, availability) values (723, 'Wiko Jerry3', 13, true);
insert into mobiles (id, model, price, availability) values (724, 'Allview P8 Energy', 9, true);
insert into mobiles (id, model, price, availability) values (725, 'Yezz Andy 4E LTE', 98, false);
insert into mobiles (id, model, price, availability) values (726, 'Celkon C7 Jumbo', 15, true);
insert into mobiles (id, model, price, availability) values (727, 'Motorola XT701', 38, false);
insert into mobiles (id, model, price, availability) values (728, 'Spice Mi-1010 Stellar Pad', 7, true);
insert into mobiles (id, model, price, availability) values (729, 'Lenovo K12', 43, false);
insert into mobiles (id, model, price, availability) values (730, 'verykool s728', 31, false);
insert into mobiles (id, model, price, availability) values (731, 'HTC Sensation XE', 26, true);
insert into mobiles (id, model, price, availability) values (732, 'BlackBerry Q10', 80, false);
insert into mobiles (id, model, price, availability) values (733, 'Realme XT', 22, true);
insert into mobiles (id, model, price, availability) values (734, 'Archos 50 Cobalt', 64, true);
insert into mobiles (id, model, price, availability) values (735, 'Nokia 1616', 16, false);
insert into mobiles (id, model, price, availability) values (736, 'i-mobile 319', 53, true);
insert into mobiles (id, model, price, availability) values (737, 'BLU Grand Mini', 89, false);
insert into mobiles (id, model, price, availability) values (738, 'LG LG 510w', 88, false);
insert into mobiles (id, model, price, availability) values (739, 'Sony Ericsson R306 Radio', 79, false);
insert into mobiles (id, model, price, availability) values (740, 'Honor X10 Max 5G', 88, true);
insert into mobiles (id, model, price, availability) values (741, 'LG Optimus G E970', 87, true);
insert into mobiles (id, model, price, availability) values (742, 'Siemens U15', 64, true);
insert into mobiles (id, model, price, availability) values (743, 'Xiaomi Redmi Note 8', 59, false);
insert into mobiles (id, model, price, availability) values (744, 'Gionee Marathon M5 lite', 67, true);
insert into mobiles (id, model, price, availability) values (745, 'Allview X2 Soul Pro', 95, false);
insert into mobiles (id, model, price, availability) values (746, 'Samsung Galaxy Avant', 47, true);
insert into mobiles (id, model, price, availability) values (747, 'Sony Xperia R1 (Plus)', 30, true);
insert into mobiles (id, model, price, availability) values (748, 'Ulefone Armor 5S', 81, false);
insert into mobiles (id, model, price, availability) values (749, 'Xiaomi Mi 10 Lite 5G', 44, false);
insert into mobiles (id, model, price, availability) values (750, 'Micromax Canvas Evok Power Q4260', 70, false);
insert into mobiles (id, model, price, availability) values (751, 'Maxon MX-7830', 39, true);
insert into mobiles (id, model, price, availability) values (752, 'Pantech PG-3500', 72, true);
insert into mobiles (id, model, price, availability) values (753, 'Energizer Energy E20', 50, true);
insert into mobiles (id, model, price, availability) values (754, 'Motorola A1000', 71, false);
insert into mobiles (id, model, price, availability) values (755, 'Nokia 3110 classic', 7, true);
insert into mobiles (id, model, price, availability) values (756, 'Samsung U700', 3, true);
insert into mobiles (id, model, price, availability) values (757, 'Lenovo A850+', 43, false);
insert into mobiles (id, model, price, availability) values (758, 'VK Mobile VK560', 21, true);
insert into mobiles (id, model, price, availability) values (759, 'Lava Iris 503', 39, false);
insert into mobiles (id, model, price, availability) values (760, 'LG C320 InTouch Lady', 10, true);
insert into mobiles (id, model, price, availability) values (761, 'Sony Ericsson K800', 60, true);
insert into mobiles (id, model, price, availability) values (762, 'Sagem MY C-1', 61, false);
insert into mobiles (id, model, price, availability) values (763, 'Mitac MIO Explora K75', 18, false);
insert into mobiles (id, model, price, availability) values (764, 'LG U8210', 57, false);
insert into mobiles (id, model, price, availability) values (765, 'Karbonn K65 Buzz', 59, false);
insert into mobiles (id, model, price, availability) values (766, 'Panasonic Eluga A2', 94, true);
insert into mobiles (id, model, price, availability) values (767, 'Nokia 603', 63, false);
insert into mobiles (id, model, price, availability) values (768, 'Sony Ericsson Z320', 42, false);
insert into mobiles (id, model, price, availability) values (769, 'LG Tribute', 77, false);
insert into mobiles (id, model, price, availability) values (770, 'BLU Studio View XL', 52, false);
insert into mobiles (id, model, price, availability) values (771, 'Kyocera Presto S1350', 5, true);
insert into mobiles (id, model, price, availability) values (772, 'Apple iPad Pro 11 (2018)', 37, true);
insert into mobiles (id, model, price, availability) values (773, 'Benefon Vega', 96, true);
insert into mobiles (id, model, price, availability) values (774, 'Vodafone 830i', 100, false);
insert into mobiles (id, model, price, availability) values (775, 'Ulefone Watch Pro', 22, true);
insert into mobiles (id, model, price, availability) values (776, 'Xiaomi Mi 9 Pro 5G', 34, false);
insert into mobiles (id, model, price, availability) values (777, 'Honor 30i', 91, true);
insert into mobiles (id, model, price, availability) values (778, 'Motorola Moto E6 Plus', 19, true);
insert into mobiles (id, model, price, availability) values (779, 'Infinix Hot 10 Lite', 25, false);
insert into mobiles (id, model, price, availability) values (780, 'ZTE Max XL', 1, true);
insert into mobiles (id, model, price, availability) values (781, 'Pantech G900', 77, true);
insert into mobiles (id, model, price, availability) values (782, 'Tecno Camon 15 Pro', 9, true);
insert into mobiles (id, model, price, availability) values (783, 'LG G2 mini LTE', 31, true);
insert into mobiles (id, model, price, availability) values (784, 'Lava Fuel F1', 41, false);
insert into mobiles (id, model, price, availability) values (785, 'Motorola StarTAC Rainbow', 49, true);
insert into mobiles (id, model, price, availability) values (786, 'ZTE Axon Pro', 5, true);
insert into mobiles (id, model, price, availability) values (787, 'BLU Bar Q', 69, true);
insert into mobiles (id, model, price, availability) values (788, 'Xiaomi Redmi 9C NFC', 26, true);
insert into mobiles (id, model, price, availability) values (789, 'Asus Zenfone 3 Laser ZC551KL', 26, false);
insert into mobiles (id, model, price, availability) values (790, 'Sony Ericsson M600', 56, false);
insert into mobiles (id, model, price, availability) values (791, 'HTC 10 evo', 7, true);
insert into mobiles (id, model, price, availability) values (792, 'Micromax X2i plus', 63, true);
insert into mobiles (id, model, price, availability) values (793, 'Sagem my405X', 83, true);
insert into mobiles (id, model, price, availability) values (794, 'HTC U Play', 35, false);
insert into mobiles (id, model, price, availability) values (795, 'Lenovo Z6 Pro', 22, true);
insert into mobiles (id, model, price, availability) values (796, 'Xiaomi Mi Mix', 46, false);
insert into mobiles (id, model, price, availability) values (797, 'Xiaomi Black Shark 3', 27, false);
insert into mobiles (id, model, price, availability) values (798, 'alcatel OT-813F', 52, true);
insert into mobiles (id, model, price, availability) values (799, 'Xiaomi Mi 2S', 29, true);
insert into mobiles (id, model, price, availability) values (800, 'verykool s6001 Cyprus', 89, true);
insert into mobiles (id, model, price, availability) values (801, 'Samsung Galaxy A72 5G', 21, false);
insert into mobiles (id, model, price, availability) values (802, 'OnePlus 2', 92, true);
insert into mobiles (id, model, price, availability) values (803, 'Asus Zenfone Go ZB500KL', 55, false);
insert into mobiles (id, model, price, availability) values (804, 'BenQ M775C', 68, true);
insert into mobiles (id, model, price, availability) values (805, 'Samsung S5550 Shark 2', 45, true);
insert into mobiles (id, model, price, availability) values (806, 'Sagem RC 750', 76, true);
insert into mobiles (id, model, price, availability) values (807, 'Celkon C570', 58, false);
insert into mobiles (id, model, price, availability) values (808, 'ZTE Kis 3', 40, true);
insert into mobiles (id, model, price, availability) values (809, 'Micromax X100', 15, true);
insert into mobiles (id, model, price, availability) values (810, 'Samsung C120', 7, true);
insert into mobiles (id, model, price, availability) values (811, 'Nokia 2626', 5, true);
insert into mobiles (id, model, price, availability) values (812, 'i-mobile 318', 11, false);
insert into mobiles (id, model, price, availability) values (813, 'Unnecto Air 5.0', 31, true);
insert into mobiles (id, model, price, availability) values (814, 'Sony Ericsson W760', 82, true);
insert into mobiles (id, model, price, availability) values (815, 'Nokia 216', 93, false);
insert into mobiles (id, model, price, availability) values (816, 'XOLO Q700s plus', 88, false);
insert into mobiles (id, model, price, availability) values (817, 'Amazon Kindle Fire HD (2013)', 70, true);
insert into mobiles (id, model, price, availability) values (818, 'Spice M-6262', 44, true);
insert into mobiles (id, model, price, availability) values (819, 'Honor Play 3', 97, true);
insert into mobiles (id, model, price, availability) values (820, 'Posh Equal S700', 19, false);
insert into mobiles (id, model, price, availability) values (821, 'HTC One ST', 70, true);
insert into mobiles (id, model, price, availability) values (822, 'Meizu E3', 62, true);
insert into mobiles (id, model, price, availability) values (823, 'Nokia 8800 Sapphire Arte', 97, false);
insert into mobiles (id, model, price, availability) values (824, 'LG G8S ThinQ', 42, false);
insert into mobiles (id, model, price, availability) values (825, 'Samsung C3730C', 29, false);
insert into mobiles (id, model, price, availability) values (826, 'Kyocera DuraCore E4210', 86, false);
insert into mobiles (id, model, price, availability) values (827, 'Samsung N400', 52, true);
insert into mobiles (id, model, price, availability) values (828, 'vivo Y71i', 46, true);
insert into mobiles (id, model, price, availability) values (829, 'LG Fireweb', 38, false);
insert into mobiles (id, model, price, availability) values (830, 'Xiaomi Mi Max 3', 3, false);
insert into mobiles (id, model, price, availability) values (831, 'Celkon A35k', 78, true);
insert into mobiles (id, model, price, availability) values (832, 'Palm Treo 600', 26, true);
insert into mobiles (id, model, price, availability) values (833, 'Samsung Z100', 100, false);
insert into mobiles (id, model, price, availability) values (834, 'Samsung Galaxy A50', 83, true);
insert into mobiles (id, model, price, availability) values (835, 'BLU Samba W', 95, false);
insert into mobiles (id, model, price, availability) values (836, 'Motorola QUENCH', 3, true);
insert into mobiles (id, model, price, availability) values (837, 'Sagem myZ-5', 9, true);
insert into mobiles (id, model, price, availability) values (838, 'Asus VivoTab RT TF600T', 98, false);
insert into mobiles (id, model, price, availability) values (839, 'Huawei Ascend G600', 25, true);
insert into mobiles (id, model, price, availability) values (840, 'Vodafone Smart first 6', 50, true);
insert into mobiles (id, model, price, availability) values (841, 'LG KG810', 81, true);
insert into mobiles (id, model, price, availability) values (842, 'Samsung D840', 84, false);
insert into mobiles (id, model, price, availability) values (843, 'Motorola Milestone XT883', 51, false);
insert into mobiles (id, model, price, availability) values (844, 'LG F60', 82, false);
insert into mobiles (id, model, price, availability) values (845, 'Huawei U8220', 19, false);
insert into mobiles (id, model, price, availability) values (846, 'HTC One M9s', 82, false);
insert into mobiles (id, model, price, availability) values (847, 'Pantech GB200', 80, false);
insert into mobiles (id, model, price, availability) values (848, 'Sewon SG-2200CD', 41, false);
insert into mobiles (id, model, price, availability) values (849, 'Motorola One Fusion', 35, false);
insert into mobiles (id, model, price, availability) values (850, 'Philips T539', 51, false);
insert into mobiles (id, model, price, availability) values (851, 'Nokia 1616', 74, true);
insert into mobiles (id, model, price, availability) values (852, 'Celkon C99', 99, false);
insert into mobiles (id, model, price, availability) values (853, 'Philips Xenium X600', 59, false);
insert into mobiles (id, model, price, availability) values (854, 'LG F1200', 49, false);
insert into mobiles (id, model, price, availability) values (855, 'Nokia 6020', 44, true);
insert into mobiles (id, model, price, availability) values (856, 'Motorola V525', 3, true);
insert into mobiles (id, model, price, availability) values (857, 'LG W30', 83, true);
insert into mobiles (id, model, price, availability) values (858, 'alcatel 3x (2019)', 66, true);
insert into mobiles (id, model, price, availability) values (859, 'Samsung Galaxy Tab 8.9 P7310', 79, true);
insert into mobiles (id, model, price, availability) values (860, 'Motorola EX226', 29, false);
insert into mobiles (id, model, price, availability) values (861, 'Lenovo Vibe A', 36, true);
insert into mobiles (id, model, price, availability) values (862, 'Apple iPad 2 CDMA', 35, false);
insert into mobiles (id, model, price, availability) values (863, 'LG Q Stylus', 16, true);
insert into mobiles (id, model, price, availability) values (864, 'Celkon C227', 55, true);
insert into mobiles (id, model, price, availability) values (865, 'Samsung Galaxy J1', 58, false);
insert into mobiles (id, model, price, availability) values (866, 'alcatel Evolve 2', 26, false);
insert into mobiles (id, model, price, availability) values (867, 'Celkon C607', 37, false);
insert into mobiles (id, model, price, availability) values (868, 'Spice M-940n', 2, true);
insert into mobiles (id, model, price, availability) values (869, 'Nokia 6820', 26, false);
insert into mobiles (id, model, price, availability) values (870, 'Sharp GX34', 4, false);
insert into mobiles (id, model, price, availability) values (871, 'Meizu M3x', 38, true);
insert into mobiles (id, model, price, availability) values (872, 'Vodafone 540', 32, true);
insert into mobiles (id, model, price, availability) values (873, 'Amoi H80', 6, false);
insert into mobiles (id, model, price, availability) values (874, 'Palm Treo 650', 42, true);
insert into mobiles (id, model, price, availability) values (875, 'NEC e238', 82, false);
insert into mobiles (id, model, price, availability) values (876, 'Chea 228', 53, false);
insert into mobiles (id, model, price, availability) values (877, 'verykool s4007 Leo IV', 16, false);
insert into mobiles (id, model, price, availability) values (878, 'Motorola Triumph', 82, false);
insert into mobiles (id, model, price, availability) values (879, 'Samsung B130', 50, true);
insert into mobiles (id, model, price, availability) values (880, 'Philips Xenium X519', 100, true);
insert into mobiles (id, model, price, availability) values (881, 'ZTE nubia Z5S mini NX403A', 35, false);
insert into mobiles (id, model, price, availability) values (882, 'Motorola Moto G4 Play', 20, false);
insert into mobiles (id, model, price, availability) values (883, 'Maxwest Gravity 5.5', 33, false);
insert into mobiles (id, model, price, availability) values (884, 'BQ Aquaris U2 Lite', 61, true);
insert into mobiles (id, model, price, availability) values (885, 'Nokia Lumia 530 Dual SIM', 73, true);
insert into mobiles (id, model, price, availability) values (886, 'Mitac MIO Explora K70', 72, true);
insert into mobiles (id, model, price, availability) values (887, 'Samsung Ch@t 357', 68, true);
insert into mobiles (id, model, price, availability) values (888, 'BLU Touchbook M7 Pro', 82, true);
insert into mobiles (id, model, price, availability) values (889, 'Philips D612', 90, false);
insert into mobiles (id, model, price, availability) values (890, 'Samsung N105', 11, false);
insert into mobiles (id, model, price, availability) values (891, 'Allview P10 Mini', 19, true);
insert into mobiles (id, model, price, availability) values (892, 'Nokia Lumia 830', 39, true);
insert into mobiles (id, model, price, availability) values (893, 'Micromax A300 Canvas Gold', 20, true);
insert into mobiles (id, model, price, availability) values (894, 'Samsung Galaxy A50s', 54, false);
insert into mobiles (id, model, price, availability) values (895, 'Motorola E680', 78, true);
insert into mobiles (id, model, price, availability) values (896, 'LG E2', 88, false);
insert into mobiles (id, model, price, availability) values (897, 'O2 Xphone IIm', 9, true);
insert into mobiles (id, model, price, availability) values (898, 'vivo iQOO Neo', 46, false);
insert into mobiles (id, model, price, availability) values (899, 'Maxon MX-3204', 77, true);
insert into mobiles (id, model, price, availability) values (900, 'Karbonn S1 Titanium', 16, true);
insert into mobiles (id, model, price, availability) values (901, 'BLU Studio G', 96, true);
insert into mobiles (id, model, price, availability) values (902, 'Allview P10 Style', 86, true);
insert into mobiles (id, model, price, availability) values (903, 'Samsung Gear S2 classic 3G', 52, false);
insert into mobiles (id, model, price, availability) values (904, 'Allview V1 Viper S', 6, false);
insert into mobiles (id, model, price, availability) values (905, 'O2 XDA Orbit', 39, true);
insert into mobiles (id, model, price, availability) values (906, 'Huawei Ascend Q M5660', 7, true);
insert into mobiles (id, model, price, availability) values (907, 'Mitsubishi m21i', 21, true);
insert into mobiles (id, model, price, availability) values (908, 'Lenovo A7', 61, true);
insert into mobiles (id, model, price, availability) values (909, 'Honor 7X', 86, true);
insert into mobiles (id, model, price, availability) values (910, 'HTC Ville', 91, true);
insert into mobiles (id, model, price, availability) values (911, 'Motorola KRZR K3', 8, false);
insert into mobiles (id, model, price, availability) values (912, 'Nokia Asha 503', 79, false);
insert into mobiles (id, model, price, availability) values (913, 'Panasonic Eluga U', 82, true);
insert into mobiles (id, model, price, availability) values (914, 'Micromax Selfie 2 Q4311', 21, true);
insert into mobiles (id, model, price, availability) values (915, 'Nokia N-Gage', 35, true);
insert into mobiles (id, model, price, availability) values (916, 'HTC Advantage X7500', 82, false);
insert into mobiles (id, model, price, availability) values (917, 'Wiko Sunny4', 20, true);
insert into mobiles (id, model, price, availability) values (918, 'Sewon SG-2100CS', 87, true);
insert into mobiles (id, model, price, availability) values (919, 'Bosch Com 607', 34, false);
insert into mobiles (id, model, price, availability) values (920, 'Samsung Galaxy Tab A 9.7', 62, false);
insert into mobiles (id, model, price, availability) values (921, 'Panasonic Eluga Arc 2', 9, true);
insert into mobiles (id, model, price, availability) values (922, 'ZTE Blade V9 Vita', 39, false);
insert into mobiles (id, model, price, availability) values (923, 'Asus Transformer TF101', 83, false);
insert into mobiles (id, model, price, availability) values (924, 'Neonode N1m', 18, false);
insert into mobiles (id, model, price, availability) values (925, 'Asus Zenfone 5 A500CG (2014)', 12, true);
insert into mobiles (id, model, price, availability) values (926, 'Sharp 930SH', 83, true);
insert into mobiles (id, model, price, availability) values (927, 'Oppo F5', 94, true);
insert into mobiles (id, model, price, availability) values (928, 'Motorola V235', 16, true);
insert into mobiles (id, model, price, availability) values (929, 'i-mobile TV 530', 36, true);
insert into mobiles (id, model, price, availability) values (930, 'Sewon SGD-1020', 24, true);
insert into mobiles (id, model, price, availability) values (931, 'vivo V15 Pro', 78, true);
insert into mobiles (id, model, price, availability) values (932, 'verykool s5014 Atlas', 35, false);
insert into mobiles (id, model, price, availability) values (933, 'OnePlus 6T McLaren', 81, false);
insert into mobiles (id, model, price, availability) values (934, 'Realme C2', 13, true);
insert into mobiles (id, model, price, availability) values (935, 'Vodafone 350 Messaging', 52, true);
insert into mobiles (id, model, price, availability) values (936, 'BLU Studio 5.0 II', 100, false);
insert into mobiles (id, model, price, availability) values (937, 'Siemens AP75', 35, true);
insert into mobiles (id, model, price, availability) values (938, 'BLU Energy XL', 1, true);
insert into mobiles (id, model, price, availability) values (939, 'Allview X4 Soul', 86, true);
insert into mobiles (id, model, price, availability) values (940, 'Motorola A780', 46, false);
insert into mobiles (id, model, price, availability) values (941, 'Philips W625', 68, false);
insert into mobiles (id, model, price, availability) values (942, 'Huawei nova 8 SE', 44, true);
insert into mobiles (id, model, price, availability) values (943, 'Wiko Lenny3', 48, true);
insert into mobiles (id, model, price, availability) values (944, 'Samsung U460 Intensity II', 6, true);
insert into mobiles (id, model, price, availability) values (945, 'Vodafone Chat 655', 95, false);
insert into mobiles (id, model, price, availability) values (946, 'Samsung F270 Beat', 88, true);
insert into mobiles (id, model, price, availability) values (947, 'Samsung Ch@t 222', 75, false);
insert into mobiles (id, model, price, availability) values (948, 'Huawei MediaPad X1', 54, true);
insert into mobiles (id, model, price, availability) values (949, 'Micromax Canvas Nitro 2 E311', 8, false);
insert into mobiles (id, model, price, availability) values (950, 'Samsung R680 Repp', 71, false);
insert into mobiles (id, model, price, availability) values (951, 'NEC N200', 74, true);
insert into mobiles (id, model, price, availability) values (952, 'Samsung Galaxy J3 Emerge', 81, false);
insert into mobiles (id, model, price, availability) values (953, 'Samsung E1282T', 95, false);
insert into mobiles (id, model, price, availability) values (954, 'Samsung Galaxy A01', 11, false);
insert into mobiles (id, model, price, availability) values (955, 'Energizer Hardcase H500S', 23, true);
insert into mobiles (id, model, price, availability) values (956, 'Samsung Galaxy J5', 29, true);
insert into mobiles (id, model, price, availability) values (957, 'Micromax A093 Canvas Fire', 52, true);
insert into mobiles (id, model, price, availability) values (958, 'Celkon C5050', 89, true);
insert into mobiles (id, model, price, availability) values (959, 'Archos Diamond S', 87, true);
insert into mobiles (id, model, price, availability) values (960, 'Motorola C980', 31, false);
insert into mobiles (id, model, price, availability) values (961, 'alcatel OT 556', 41, false);
insert into mobiles (id, model, price, availability) values (962, 'ZTE Blade A2', 14, false);
insert into mobiles (id, model, price, availability) values (963, 'ZTE nubia X', 14, true);
insert into mobiles (id, model, price, availability) values (964, 'Sharp GX30', 73, true);
insert into mobiles (id, model, price, availability) values (965, 'Oppo A92s', 9, true);
insert into mobiles (id, model, price, availability) values (966, 'Meizu 15 Lite', 13, true);
insert into mobiles (id, model, price, availability) values (967, 'Xiaomi Black Shark 2', 99, false);
insert into mobiles (id, model, price, availability) values (968, 'Philips X125', 87, false);
insert into mobiles (id, model, price, availability) values (969, 'Samsung Z230', 28, true);
insert into mobiles (id, model, price, availability) values (970, 'alcatel OT-978', 12, true);
insert into mobiles (id, model, price, availability) values (971, 'Celkon Win 400', 57, false);
insert into mobiles (id, model, price, availability) values (972, 'Asus Zenwatch 3 WI503Q', 79, true);
insert into mobiles (id, model, price, availability) values (973, 'Gigabyte GSmart G1342 Houston', 83, false);
insert into mobiles (id, model, price, availability) values (974, 'Celkon C605', 100, true);
insert into mobiles (id, model, price, availability) values (975, 'Plum Play', 35, true);
insert into mobiles (id, model, price, availability) values (976, 'Karbonn K11+', 31, false);
insert into mobiles (id, model, price, availability) values (977, 'Samsung Galaxy A40', 33, true);
insert into mobiles (id, model, price, availability) values (978, 'Samsung C3300K Champ', 61, true);
insert into mobiles (id, model, price, availability) values (979, 'Tecno Camon 11 Pro', 27, false);
insert into mobiles (id, model, price, availability) values (980, 'Philips Xenium 9@9v', 34, false);
insert into mobiles (id, model, price, availability) values (981, 'Xiaomi Redmi Note 10', 8, true);
insert into mobiles (id, model, price, availability) values (982, 'Sony Ericsson Z610', 55, false);
insert into mobiles (id, model, price, availability) values (983, 'Amoi A310', 6, true);
insert into mobiles (id, model, price, availability) values (984, 'Allview Allwatch', 84, false);
insert into mobiles (id, model, price, availability) values (985, 'HTC Radar', 52, false);
insert into mobiles (id, model, price, availability) values (986, 'Samsung Galaxy S9+', 18, true);
insert into mobiles (id, model, price, availability) values (987, 'Sony Ericsson W902', 15, true);
insert into mobiles (id, model, price, availability) values (988, 'Posh Lynx A100', 32, false);
insert into mobiles (id, model, price, availability) values (989, 'Apple iPad mini Wi-Fi', 69, false);
insert into mobiles (id, model, price, availability) values (990, 'Micromax Unite 4 plus', 25, true);
insert into mobiles (id, model, price, availability) values (991, 'HTC One X9', 99, true);
insert into mobiles (id, model, price, availability) values (992, 'Oppo A73', 31, true);
insert into mobiles (id, model, price, availability) values (993, 'Icemobile Cenior', 74, false);
insert into mobiles (id, model, price, availability) values (994, 'verykool s4513 Luna II', 68, false);
insert into mobiles (id, model, price, availability) values (995, 'LG Optimus LTE LU6200', 30, false);
insert into mobiles (id, model, price, availability) values (996, 'BlackBerry Torch 9800', 97, true);
insert into mobiles (id, model, price, availability) values (997, 'Karbonn A3', 75, false);
insert into mobiles (id, model, price, availability) values (998, 'Huawei Ascend Y220', 97, true);
insert into mobiles (id, model, price, availability) values (999, 'Orange Barcelona', 64, false);
insert into mobiles (id, model, price, availability) values (1000, 'Icemobile Prime Plus', 28, false);
